### ISSUE TITLE
Sphinx Ambassador only lets you choose from avatar cards and cards from Oath of the Gatewatch

### ISSUE THREAD

**Issue by ZedruuTheGoathearted** [PennyDreadfulMTG/modo-bugs#1008]
**What is the expected behaviour of the card?**
 
You search your opponent's library for a card. They have to guess what they might have gotten, and if they guess incorrectly you get to put the card into play if you searched for a creature.

**What is the actual behaviour of the card?**
 
When guessing a card, your opponent can only name cards from Oath of the Gatewatch and vanguard avatar cards.

**Screenshot**
![Capture](https://user-images.githubusercontent.com/100009752/154785398-64e333e8-f62a-4ce3-b1cd-377dff001f54.PNG)
![Capture2](https://user-images.githubusercontent.com/100009752/154785402-58de69c9-28d6-486b-92dd-9a4bc97b4016.PNG)
![Capture3](https://user-images.githubusercontent.com/100009752/154785403-1f0cf048-2115-4f02-9b58-51b596be99e4.PNG)
![Capture4](https://user-images.githubusercontent.com/100009752/154785408-aa62e0db-415b-45df-964d-4193dcd89baa.PNG)

**Please provide a list of affected cards**
Affects: [Sphinx Ambassador]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Sphinx%20Ambassador/" height="300px">

**Comment by Rowsol** [comment]
haha

**Comment by MultiDragon** [comment]
fixed
![image](https://user-images.githubusercontent.com/52964431/167668880-bc6c4ade-5c31-444c-8975-431cdaf4038c.png)
