### ISSUE TITLE
While at -3 life or less, Ad Nauseam does not make you lose life equal to the mana value of the revealed card unless that card's mana value is 1.

### ISSUE THREAD

**Issue by datrobino** [PennyDreadfulMTG/modo-bugs#1011]
**What is the expected behaviour of the card?**
 - you take damage equal to the revealed cards mv

**What is the actual behaviour of the card?**
 - you dont take damage equal to the revealed cards mv unless the revealed cards mv is 1 if your life total is -3 or less

**Screenshot**
![image](https://user-images.githubusercontent.com/85389721/155883089-f00c23d6-42ad-4a18-b76a-7e4b6aa8d85f.png)
![image](https://user-images.githubusercontent.com/85389721/155883097-cdc12bf8-c07f-48bb-9205-42ef27b153f6.png)
(notice the revealed simian spirit guide)
**Please provide a list of affected cards**
Affects: [Ad Nauseam]
See Also: [Angel's Grace]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Ad%20Nauseam/" height="300px"><img src="https://pennydreadfulmagic.com/image/Angel%27s%20Grace/" height="250px">

**Comment by MultiDragon** [comment]
Never matters while playing most of the decks with Ad Nauseam. Known things it affects: gaining life to go over 0, Death's Shadow and similar

**Comment by datrobino** [comment]
fixed
