### ISSUE TITLE
Akiri, Fearless Voyager triggers when it attacks with no attached equipment

### ISSUE THREAD

**Issue by Dynme** [PennyDreadfulMTG/modo-bugs#1014]
**What is the expected behaviour of the card?**
 Akiri, Fearless Voyager should draw a card when you attack with one or more equipped creatures.

**What is the actual behaviour of the card?**
 Akiri, Fearless Voyager draws a card when it attacks despite not being equipped. Tested again in a solo game, Akiri drew a card even with no equipment in play when attacking with another creature.

**Screenshot**
(https://i.imgur.com/O3XKBPK.png)

**Please provide a list of affected cards**
Affects: [Akiri, Fearless Voyager]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Akiri%2C%20Fearless%20Voyager/" height="300px">

**Comment by MultiDragon** [comment]
Fixed according to JayceArveduin.

![image](https://user-images.githubusercontent.com/52964431/169639128-7a56fa32-712f-48cc-a839-3d90086bf9e8.png)
