### ISSUE TITLE
Bitter Ordeal does not copy itself with its Gravestorm ability

### ISSUE THREAD

**Issue by professorg** [PennyDreadfulMTG/modo-bugs#1015]
**What is the expected behaviour of the card?**
 - When Bitter Ordeal is cast, it is copied for each permanent that entered a graveyard this turn.

**What is the actual behaviour of the card?**
 - When Bitter Ordeal is cast, it is not copied and resolves only once.

**Screenshot**
![image](https://user-images.githubusercontent.com/12582971/158123898-0bcb5777-cade-479d-9f94-abea55daf284.png)

**Please provide a list of affected cards**
Affects: [Bitter Ordeal]

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by professorg** [comment]
Milled permanents are not permanent cards. Working as intended.

**Comment by datrobino** [comment]
correction: milled cards are permanent cards, not permanents
