### ISSUE TITLE
Bloodbraid Elf cascading into toxic deluge restarts the game

### ISSUE THREAD

**Issue by OperaJon** [PennyDreadfulMTG/modo-bugs#1019]
**What is the expected behaviour of the card?**
 - Cascade ability from Bloodbraid Elf casts Toxic Deluge

**What is the actual behaviour of the card?**
 - Causes MTGO to replay all actions of game and then start a new game with both players at full clock

**Screenshot**
Currently Unconfirmed.
![image](https://user-images.githubusercontent.com/95944212/160877376-2b90b1bd-18bd-4496-8357-6d8c9cc99481.png)

**Please provide a list of affected cards**
Affects: [Toxic Deluge]
See Also: [Bloodbraid Elf]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Toxic%20Deluge/" height="300px"><img src="https://pennydreadfulmagic.com/image/Bloodbraid%20Elf/" height="250px">

**Comment by OperaJon** [comment]
No, I could not click anything, never got to choose an x or anything, I think it started when I clicked to cast Toxic Deluge

**Comment by MultiDragon** [comment]
moved to #1019
