### ISSUE TITLE
Archfiend of Depravity causes the game to restart when it's trigger resolves

### ISSUE THREAD

**Issue by Rowsol** [PennyDreadfulMTG/modo-bugs#1020]
**What is the expected behaviour of the card?**
 - sacrifice some guys

**What is the actual behaviour of the card?**
 - game resets

**Screenshot**
https://ibb.co/FWLNCvx

**Please provide a list of affected cards**
Affects: [Archfiend of Depravity]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Archfiend%20of%20Depravity/" height="300px">

**Comment by MultiDragon** [comment]
not an actual bug

![image](https://user-images.githubusercontent.com/52964431/167638198-342009cc-82b7-4341-ad1d-477ce1079f61.png)

**Comment by Rowsol** [comment]
> not an actual bug
> 
> ![image](https://user-images.githubusercontent.com/52964431/167638198-342009cc-82b7-4341-ad1d-477ce1079f61.png)

I can assure you it is. I've had it happen back to back in commander multiplayer. Just because it works in solitare means fuck all.

**Comment by Kalioc** [comment]
The behaviors need to be more descriptive so we can actually reproduce bugs, like when is the game resetting before or after sacrifices, if they selected one or two creatures.

**Comment by Rowsol** [comment]
> The behaviors need to be more descriptive so we can actually reproduce bugs, like when is the game resetting before or after sacrifices, if they selected one or two creatures.

Both times it crashed as soon as people passed around and right before it was time to sacrifice.
