### ISSUE TITLE
Strongarm Tactics is not symmetrical

### ISSUE THREAD

**Issue by datrobino** [PennyDreadfulMTG/modo-bugs#1021]
**What is the expected behaviour of the card?**
 - the card should effect both players

**What is the actual behaviour of the card?**
 - the card doesnt effect both players

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Strongarm Tactics]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Strongarm%20Tactics/" height="300px">

**Comment by bakert** [comment]
Reported fixed by GoldfishMan2136 on Discord
