### ISSUE TITLE
Modal permanents only let you choose each mode once

### ISSUE THREAD

**Issue by counter-spell** [PennyDreadfulMTG/modo-bugs#1022]
**What is the expected behaviour of the card?**
- Every time you trigger the ability on these permanents, you should be able to choose any option
**What is the actual behaviour of the card?**
 - When you trigger the ability you must choose an option you havent chosen before

**Screenshot**
![Screenshot (27)](https://user-images.githubusercontent.com/104592560/165826116-71ddb577-3dd6-42db-bc2a-43dfdc616bed.png)

**Please provide a list of affected cards**
Affects: [Tectonic Giant], [Life of Toshiro Umezawa], [Abiding Grace]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Tectonic%20Giant|Life%20of%20Toshiro%20Umezawa|Abiding%20Grace/" height="300px">

**Comment by jmeka** [comment]
Solitaire game: first picked the deal 3 option, then i wasnt prompted to pick, instead was forced to exile the top 2, then the next turn i couldnt even choose either option.
![Screenshot 2022-04-28 145640](https://user-images.githubusercontent.com/28836887/165826466-4be145d1-6e01-45c7-a59f-f3889de7a644.png)

**Comment by datrobino** [comment]
its all modal permanents
![image](https://user-images.githubusercontent.com/85389721/165826765-d24a71b6-95b8-4804-b7ce-0cb8cb39d896.png)

**Comment by datrobino** [comment]
list of presumed bugged cards: glorious sunrise, triskadekaphobia, energy chamber, dreamshackle geist, blizzard specter, kitsune ace, ojutai exemplars, quiet disrepair, etherwrought page, putrid warrior

**Comment by jmeka** [comment]
seems like this is fixed with the 5/4 update
