### ISSUE TITLE
Gallia of the Endless Dance's ability does not draw cards.

### ISSUE THREAD

**Issue by EdLates** [PennyDreadfulMTG/modo-bugs#1024]
**What is the expected behaviour of the card?**
 - When you discard a card at random you draw 2 cards

**What is the actual behaviour of the card?**
 - When you discard nothing happens

**Screenshot**
https://imgur.com/a/UC55f7w

**Please provide a list of affected cards**
Affects: [Gallia of the Endless Dance]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Gallia%20of%20the%20Endless%20Dance/" height="300px">

**Comment by Rowsol** [comment]
https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-september-13-2022

they say they fixed it
