### ISSUE TITLE
Etchings of the Chosen (PRM) doesn't display it's set symbol

### ISSUE THREAD

**Issue by Rowsol** [PennyDreadfulMTG/modo-bugs#1028]
**What is the expected behaviour of the card?**
 - It should show the promo symbol

**What is the actual behaviour of the card?**
 - nothing is there

**Screenshot**
![etchings](https://user-images.githubusercontent.com/35880360/171938988-c1b58b4c-ac0f-4e25-840a-d2b064b4ce59.png)

**Please provide a list of affected cards**
Affects: [Etchings of the Chosen]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Etchings%20of%20the%20Chosen/" height="300px">

**Comment by datrobino** [comment]
not relevent

**Comment by datrobino** [comment]
also fixed
