### ISSUE TITLE
Dragonskull summit does not come in untapped when entering due to Worldgorger dragon with mountain condition true

### ISSUE THREAD

**Issue by MimberyEarth** [PennyDreadfulMTG/modo-bugs#1033]
**What is the expected behaviour of the card?**
 - Mountain is in play. Worldgorger dragon leaves the battlefield having exiled 3 dragonskull summits and a mountain with its ETB effect. Mountain enters untapped, Dragonskull Summit enters untapped due to its "enters the battlefield tapped unless you control a mountain or a swamp' text.

**What is the actual behaviour of the card?**
 - In the above scenario, the Mountain enters untapped but the Dragonskull summits enter tapped.

**Screenshot**
(Attach a screenshot or video here)
![image](https://user-images.githubusercontent.com/22524793/176964869-edede459-2e6f-4d53-b332-7d6dbf5a7cc0.png)

**Please provide a list of affected cards**
Affects: [Dragonskull Summit] [Worldgorger Dragon]

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by datrobino** [comment]
i believe this is how its supposed to work

**Comment by MimberyEarth** [comment]
I understand and later stated that I would not have won without a damage source, in case anyone was wondering.

**Comment by MimberyEarth** [comment]
> i believe this is how its supposed to work

Why would that be?

**Comment by datrobino** [comment]
![image](https://user-images.githubusercontent.com/85389721/176965104-a82b91fc-05c2-4ef5-8d56-a7c9a937705e.png)

**Comment by MimberyEarth** [comment]
I had a mountain under my control, as stated in the original post. It also entered with a mountain, thus 2 mountains.

**Comment by datrobino** [comment]
ok one sec im going to check the game log

**Comment by datrobino** [comment]
oh wait pdbot is down

**Comment by MimberyEarth** [comment]
I was specific about making sure I had a mountain before-hand, you can ask my opponent.

**Comment by datrobino** [comment]
yeah one sec im checking to see if its replicitable

**Comment by datrobino** [comment]
when i try it in single player it functions correctly

**Comment by datrobino** [comment]
assuming the steps to replicate are
cast worldgorger exiling dragonskull
play mountain
worldgorger leaves

**Comment by MimberyEarth** [comment]
As per my replay of the game, apparently, I played a Dragonskull Summit, not a mountain, I seem to be remembering wrongly.

**Comment by MimberyEarth** [comment]
![image](https://user-images.githubusercontent.com/22524793/176965981-bdd18a22-d6d8-4ade-98e9-d84671694e1b.png)
