### ISSUE TITLE
Peregrine Drake causes the game to restart when it's triggered ability resolves

### ISSUE THREAD

**Issue by Rowsol** [PennyDreadfulMTG/modo-bugs#1041]
**What is the expected behaviour of the card?**
 - You untap 5 lands

**What is the actual behaviour of the card?**
 - The game stalls and then resets when attempting to resolve the ability
 
**Please provide a list of affected cards**
Affects: [Peregrine Drake], [Palinchron]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Peregrine%20Drake/" height="300px">
![Annotation 2022-08-31 174911](https://user-images.githubusercontent.com/35880360/187791514-a80a8faf-3de8-4bd1-a177-07f93981852f.png)

**Comment by Rowsol** [comment]
It doesn't matter how many lands you try to untap and the problem extends to Palinchron as well.

**Comment by datrobino** [comment]
i have not been able to reproduce this

**Comment by Rowsol** [comment]
Strange. Maybe it only happens in solitaire, or commander solitaire?

**Comment by datrobino** [comment]
i tried it in solitaire

**Comment by datrobino** [comment]
maybe its a commander thing

**Comment by Rowsol** [comment]
It works fine for me in freeform but it happened back to back in commander solitaire. Are you available to test with in the commander room?

**Comment by datrobino** [comment]
sure

**Comment by Rowsol** [comment]
I need your mtgo name

**Comment by datrobino** [comment]
room up

**Comment by datrobino** [comment]
seems to work properly?

**Comment by Rowsol** [comment]
Well what do you know, now it works. The many mysteries of life.
