### ISSUE TITLE
Selvala, Explorer Returned gives 1 mana and 0 life when tapped for mana regardless of the amount of nonland cards revealed

### ISSUE THREAD

**Issue by Rowsol** [PennyDreadfulMTG/modo-bugs#1043]
**What is the expected behaviour of the card?**
 - you get 1 mana and 1 life for each nonland revealed

**What is the actual behaviour of the card?**
 - you get 1 mana and 0 life regardless of the amount of nonland cards revealed

**Please provide a list of affected cards**
Affects: [Selvala, Explorer Returned]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Selvala%2C%20Explorer%20Returned/" height="300px">

![Screenshot (255)](https://user-images.githubusercontent.com/35880360/188249561-f9c305ab-5888-4025-ae56-3a68096e7f15.png)

**Comment by Rowsol** [comment]
Tested two times, the first tap was 3 nonlands and the second was the picture you see above.

**Comment by datrobino** [comment]
confirmed

**Comment by Broboat** [comment]
Confirmed this is still happening.

**Comment by Rowsol** [comment]
fixed 
https://forums.mtgo.com/index.php?threads/selvala-explorer-returned-parley-ability-not-working-correctly.537/#post-1219
