### ISSUE TITLE
Joraga Treespeaker's Level Up ability isn't stopped by phasing out

### ISSUE THREAD

**Issue by TGower** [PennyDreadfulMTG/modo-bugs#1049]
**What is the expected behaviour of the card?**
 -  If a creature with a level up is phased out while the level up ability is on the stack, the creature should not have a level counter added to it. Relevant rule:
 - 702.26b If a permanent phases out, its status changes to “phased out.” Except for rules and effects that specifically mention phased-out permanents, a phased-out permanent is treated as though it does not exist. It can’t affect or be affected by anything else in the game. A permanent that phases out is removed from combat.

**What is the actual behaviour of the card?**
 - Phasing out Joraga Treespeaker in response to the level up ability will have the level counter added to it while phased out.

**Screenshot**
https://imgur.com/a/vnIJycZ

**Please provide a list of affected cards**
Affects: [Joraga Treespeaker]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Joraga%20Treespeaker/" height="300px">

**Comment by datrobino** [comment]
fixed
