### ISSUE TITLE
Mizzix's Mastery doesn't allow you to cast the exiled cards

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#1058]
**What is the expected behaviour of the card?**
 - You exile cards, copy them, then cast the copies.

**What is the actual behaviour of the card?**
 - You exile cards.  That's it.

**Support Forum Thread**
Forum Post: https://forums.mtgo.com/index.php?threads/mizzixs-mastery-mechanic-fails.205/

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Mizzix's Mastery]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Mizzix%27s%20Mastery/" height="300px">

**Comment by Wizzerinus** [comment]
Fixed in daybreak
