### ISSUE TITLE
Thran Vigil Triggers Twice When Creatures Enter The Battlefield Upon Leaving the Graveyard

### ISSUE THREAD

**Issue by ciabhanconnelly** [PennyDreadfulMTG/modo-bugs#1062]
**What is the expected behaviour of the card?**
Thran Vigil triggers once allowing a +1/+1 counter to be placed on a creature whenever a creature enters the battlefield.

**What is the actual behaviour of the card?**
Thran Vigil triggers twice if the creature leaving the graveyard does so because it is entering the battlefield (for example due to Unearth, Persist, or a reanimation effect). 

**Screenshot**
![Vigil Bug](https://user-images.githubusercontent.com/59980216/207201524-1e869f90-0601-4601-9f06-ac12ecc0e520.PNG)

**Please provide a list of affected cards**
Affects: [Thran Vigil], many cards that cause creatures to return to the battlefield from grave

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

https://forums.mtgo.com/index.php?threads/thran-vigil-activates-twice-the-effect-when-a-creature-leaves-the-graveyard.251/

**Comment by Rowsol** [comment]
fixed as of today
https://www.mtgo.com/news/mtgo-blog-12132022

**Comment by datrobino** [comment]
please test bugs before closing them in the future

**Comment by silasary** [comment]
Fixed as of tomorrow.  The patch notes go up a day early.

**Comment by Tygrak** [comment]
![obrazek](https://user-images.githubusercontent.com/23155456/207931449-ba5ae5a0-59c5-4752-b177-aadfbf8f9c36.png)

Indeed fixed
