### ISSUE TITLE
Jugan Defends The Temple / Remnant of the Rising Star paying X does not put any counters on creature

### ISSUE THREAD

**Issue by KidBar** [PennyDreadfulMTG/modo-bugs#1077]
**What is the expected behaviour of the card?**
 -
Whenever another creature enters the battlefield under your control, you may pay X. When you do, put X +1/+1 counters on that creature. 
**What is the actual behaviour of the card?**
 -Whenever another creature enters the battlefield under your control, you may pay X. When you do, do not put any counters on that creature. 

**Support Forum Thread**

Forum Post:

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: Jugan Defends The Temple / Remnant of the Rising Star

**Card Images**
 

Forum Post: https://forums.mtgo.com/index.php?threads/how-to-report-and-upvote-bugs.21/

**Comment by saebelma** [comment]
I would like to confirm this bug.

**Comment by datrobino** [comment]
couldnt replicate
