### ISSUE TITLE
Karn, Scion of Urza eats your next step after +1

### ISSUE THREAD

**Issue by nex3** [PennyDreadfulMTG/modo-bugs#1079]
After you resolve Karn's +1, you draw a card as normal
 -

After you resolve Karn's +1, the next time you would draw a card you don't instead
 -

**Support Forum Thread**

Forum Post: https://forums.mtgo.com/index.php?threads/karn-scion-of-urza-skipped-draw-step-bug.880/

**Please provide a list of affected cards**
Affects: Karn, Scion of Urza

**Card Images**

**Comment by Rowsol** [comment]
fixed
https://www.mtgo.com/news/mtgo-blog-5162023
