### ISSUE TITLE
Disciple of the vault incorrectly prompts you to use {opponents name's} ability instead of its ability implying your opponent has the life loss ability

### ISSUE THREAD

**Issue by alternatwrecker** [PennyDreadfulMTG/modo-bugs#1088]
**What is the expected behaviour of the card?**
 -
target opponent loses 1 life
**What is the actual behaviour of the card?**
 -
loss of 1 life, but the game prompts you to use your {opponent's name} ability to do so
**Support Forum Thread**

Forum Post:

**Screenshot**
Currently Unconfirmed.
![image](https://github.com/PennyDreadfulMTG/modo-bugs/assets/79876931/62dca451-7051-40ac-9d13-f762d785d66b)

**Please provide a list of affected cards**
Affects: [Disciple of the Vault]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Disciple%20of%20the%20Vault/" height="300px">

Forum Post: https://forums.mtgo.com/index.php?threads/how-to-report-and-upvote-bugs.21/

**Comment by Wizzerinus** [comment]
Closing because this is a generic bug which exists on many cards and even many random scenarios.
