### ISSUE TITLE
Pillar of the Paruns cannot pay for split costs

### ISSUE THREAD

**Issue by Wizzerinus** [PennyDreadfulMTG/modo-bugs#1089]
**What is the expected behaviour of the card?**
 - Pillar of the Paruns can pay for split cards if they're multicolored

**What is the actual behaviour of the card?**
 - It can't

**Support Forum Thread**

Forum Post: https://forums.mtgo.com/index.php?threads/pillar-of-the-paruns-cannot-pay-the-costs-of-split-cards.1463/

**Screenshot**

https://github.com/PennyDreadfulMTG/modo-bugs/assets/52964431/c801f290-541d-4205-b2b0-75fc9141dc52

**Please provide a list of affected cards**
Affects: [Pillar of the Paruns]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Pillar%20of%20the%20Paruns/" height="300px">

Forum Post: https://forums.mtgo.com/index.php?threads/how-to-report-and-upvote-bugs.21/

**Comment by datrobino** [comment]
fixed
