### ISSUE TITLE
Primal Wellspring doesn't copy spells cast by the third chapter of Founding the Third Path

### ISSUE THREAD

**Issue by watchwander** [PennyDreadfulMTG/modo-bugs#1091]
**What is the expected behaviour of the card?**
 - Using mana from Primal Wellspring copies spells cast by Founding the Third Path

**What is the actual behaviour of the card?**
 - The spell does not get copied

**Support Forum Thread**

Forum Post:

**Screenshot**
![image](https://github.com/PennyDreadfulMTG/modo-bugs/assets/130810855/3e17c223-53cd-4756-ac9b-29a03fcf1fda)

**Please provide a list of affected cards**
Affects: [Primal Amulet] [Founding the Third Path]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Primal%20Amulet|Founding%20the%20Third%20Path/" height="300px">

**Comment by bakert** [comment]
<img width="1732" alt="image" src="https://github.com/user-attachments/assets/41ab1808-f2de-4bfc-84b5-3b6960cfdc82">

This was fixed at some point.
