### ISSUE TITLE
Legion Warboss tokens incorrectly have bluetext implying they must attack each turn if able – it's just this turn

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/modo-bugs#1108]
**What is the expected behaviour of the card?**
 - A token created by Legion Warboss says on it "attacks this turn if able"

**What is the actual behaviour of the card?**
 - "Attacks each combat if able". (It goes away after the turn passes.)

**Support Forum Thread**

Forum Post:

**Screenshot**
<img width="974" alt="Screenshot 2024-04-04 at 18 22 04" src="https://github.com/PennyDreadfulMTG/modo-bugs/assets/1541/75693cdd-f4f6-4cf6-bf02-2e2405a341a5">

**Please provide a list of affected cards**
Affects: [Legion Warboss]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Legion%20Warboss/" height="300px">

**Comment by datrobino** [comment]
![image](https://github.com/user-attachments/assets/c03dc0a0-8cb1-4072-b74c-ebd8c1ab751c)
fixed
