### ISSUE TITLE
Deputy of Detention doesn't exile morphs

### ISSUE THREAD

**Issue by chaosblackdoom** [PennyDreadfulMTG/modo-bugs#1110]
**What is the expected behaviour of the card?**
 
Deputy of Detention will exile morphs

**What is the actual behaviour of the card?**
 
Deputy of Detention doesn't exile morphs, no prompt either.

**Support Forum Thread**

Forum Post: https://forums.mtgo.com/index.php?threads/deputy-of-detention-cannot-exile-morphs.2088/

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Deputy of Detention]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Deputy%20of%20Detention/" height="300px">

**Comment by datrobino** [comment]
not bugged
