### ISSUE TITLE
Lurrus of the Dream-Den will not allow you to pay more than 2 mana when casting using its ability

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/modo-bugs#1113]
**What is the expected behaviour of the card?**
 - Once during each of your turns, you may cast a permanent spell with mana value 2 or less from your graveyard. If this were, say, a Chalice of the Void you'd be able to cast it with any value for X that you can pay for.

**What is the actual behaviour of the card?**
 - You may cast cards like Chalice of the Void from your graveyard but the total mana spent is restricted to be 2 or less.

**Support Forum Thread**

Forum Post: https://forums.mtgo.com/index.php?threads/lurrus-of-the-dream-den-will-not-allow-you-to-pay-more-than-2-mana-when-casting-using-its-ability.2299/

**Screenshot**

<img width="1571" alt="lurrus-chalice" src="https://github.com/PennyDreadfulMTG/modo-bugs/assets/1541/1c232ab3-bb0c-4cef-9094-01c699f84f98">

<img width="1568" alt="lurrus-astral-cornucopia" src="https://github.com/PennyDreadfulMTG/modo-bugs/assets/1541/92843a73-175a-4f74-b9d6-62eafa4d132e">

<img width="1570" alt="lurrus-stonecoil-serpent" src="https://github.com/PennyDreadfulMTG/modo-bugs/assets/1541/4fe87caa-ace1-46d1-ac5b-baf8599e404e">

**Please provide a list of affected cards**
Affects: [Lurrus of the Dream-Den]

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by Wizzerinus** [comment]
thats actually a lie:
```
For spells with {X} in their mana costs, use the value chosen for X to determine the spell's mana value. For example, if a permanent spell costs {X}{W}, you could cast it with X as 1 but not as 2. 
```
