### ISSUE TITLE
conspiracy unraveler does not allow using collect evidence to cast a spell with flashback from the graveyard

### ISSUE THREAD

**Issue by rbibbs** [PennyDreadfulMTG/modo-bugs#1116]
**What is the expected behaviour of the card?**
 - To allow you to collect evidence 10 rather than pay the mana cost for all spells, including those with flashback from the graveyard (suggested by the oracle text example: "If you are casting a spell from your graveyard **(for example, a spell with flashback)** you can’t also exile that card to pay the alternative collect evidence cost offered by Conspiracy Unraveler. (2024-02-02)")

**What is the actual behaviour of the card?**
 - Does not allow collecting evidence 10 to pay for the flashback cost of spells (e.g. Unburial Rites). Allows collecting evidence 10 to pay for spells other than those using flashback, even those cast from the graveyard (e.g. Hogaak). 

**Support Forum Thread**

Forum Post: [https://forums.mtgo.com/index.php?threads/conspiracy-unraveler-not-working-with-flashback.2459/](https://forums.mtgo.com/index.php?threads/conspiracy-unraveler-not-working-with-flashback.2459/)

**Screenshot**
![conspiracyunravelerbug](https://github.com/user-attachments/assets/cdb9eaea-7069-44ba-9eb6-46a3d10b918a)

**Please provide a list of affected cards**
Affects: [Conspiracy Unraveler]

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by Wizzerinus** [comment]
This is not a bug. The rulings on this card are gaslighting you because you aren't supposed to do this. (Both unraveler and flashback are alternative costs)
