### ISSUE TITLE
Genju of the Fields does not cause you to gain life upon dealing damage

### ISSUE THREAD

**Issue by SirPollux** [PennyDreadfulMTG/modo-bugs#122]
Affects: [Genju of the Fields]
 <img src="https://api.scryfall.com/cards/named?exact=Genju%20of%20the%20Fields&format=image" width="300px">

**Comment by BackAlleyG** [comment]
### Screenshot:

![image](https://user-images.githubusercontent.com/31076829/36134966-00896f0c-1056-11e8-902b-5ef69398e0c4.png)

Note: The test from which the picture was from was done in solitaire incase that wasn't clear from the picture.

**Comment by bakert** [comment]
Verified again 2018-05-19

**Comment by BackAlleyG** [comment]
Tested it again and it has been fixed.

Covered in build notes of [ June 19th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-june-19-2018-2018-06-19).

>Granting "Whenever this creatures deals damage, you gain that much life" effects now work correctly
