### ISSUE TITLE
[Armor of thorns] The sacrifice ability doesn't triggered at the cleanup step

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#130]

**Comment by silasary** [comment]
Does this affect all the auras in this cycle?

**Comment by stash86** [comment]
Haven't try with the other similar auras

On Jul 30, 2017, at 21:56, Katelyn Gigante <notifications@github.com> wrote:

Does this affect all the auras in this cycle?

―

**Comment by jmeka** [comment]
This particular card is working as intended. 
![bugss4](https://user-images.githubusercontent.com/28836887/29202746-02621608-7e39-11e7-9f53-6f4da70aa423.JPG)
![bugss5](https://user-images.githubusercontent.com/28836887/29202745-02620cee-7e39-11e7-98e9-4b36844693a6.JPG)
![bugss6](https://user-images.githubusercontent.com/28836887/29202747-0266c9dc-7e39-11e7-869c-82b767a83e3c.JPG)
