### ISSUE TITLE
Chandra Nalaar Ultimate ability (Chandra's -8) does not count as damage from a planeswalker.

### ISSUE THREAD

**Issue by jmeka** [PennyDreadfulMTG/modo-bugs#132]
![capture](https://user-images.githubusercontent.com/28836887/28847155-39550c56-76dc-11e7-9959-9e632a57fbde.JPG)
This affects things like Pyromancer's Gauntlet or Chandra's Phoenix.
It does count as a red source, as tested with Embermaw Hellion. 

Affects: [Chandra Nalaar]
 <img src="https://api.scryfall.com/cards/named?exact=Chandra%20Nalaar&format=image" width="300px">

**Comment by silasary** [comment]
Reported Fixed by Briar Moss
