### ISSUE TITLE
[Mass Polymorph] Exile ability does not count exiled tokens

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#14]

**Comment by jmeka** [comment]
This card works as intended. 
![bugss2](https://cloud.githubusercontent.com/assets/28836887/26481207/6a5b8ae6-41ad-11e7-8149-3f82c024e28a.JPG)
![bugss3](https://cloud.githubusercontent.com/assets/28836887/26481208/6a5c6de4-41ad-11e7-81b5-e57cf3c6bcab.JPG)

**Comment by silasary** [comment]
Thanks 😄
