### ISSUE TITLE
[Smokebraider] Can't use mana to cast Bloodbriar

### ISSUE THREAD

**Issue by paupPiiX** [PennyDreadfulMTG/modo-bugs#147]
[Smokebraider] Can't use mana to cast [Bloodbriar]. I've tested other elementals and elemental abilities, works fine.

**Comment by silasary** [comment]
I think this is related to the same bug as Cavern of Souls and Ally Encampment. (MTGO-3165)

**Comment by silasary** [comment]
To elaborate, mana sources that are specifically typed only work if a creature has the specified type in the first entry.

Because Bloodbriar is a `Plant Elemental`, it only counts as a plant as far as the bug is concerned.

**Comment by paupPiiX** [comment]
I thought as much. Thank you.

**Comment by silasary** [comment]
Fixed in Yesterday's downtime 😁
