### ISSUE TITLE
Creatures returned with Puppeteer Clique are exiled at the end of any turn, not just the controller's

### ISSUE THREAD

**Issue by Isvan3** [PennyDreadfulMTG/modo-bugs#178]
Affects: [Puppeteer Clique]
 <img src="https://api.scryfall.com/cards/named?exact=Puppeteer%20Clique&format=image" width="300px">

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ May 15th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-may-15-2018).

>Puppeteer Clique now correctly only exiles the targeted creature at the beginning of your end step.
