### ISSUE TITLE
If you target an Icefall Regent with a fused split card, you must pay {2} for each side of the split card, for a total of {4}

### ISSUE THREAD

**Issue by PsyMar** [PennyDreadfulMTG/modo-bugs#208]
**What is the correct behaviour?**
Icefall regent causes spells that are targetting it to cost {2} more. If Icefall regent get targeted by a fused spell where both sides of the spell targetting Icefall, it still will cost {2} more because the spell counted as 1 spell

**What is the current behaviour?**
I targetted one twice with [Turn // Burn] and had to pay 9 mana instead of 7 because it targetted the one icefall regent twice

![image](https://user-images.githubusercontent.com/5404124/32138653-40154ec6-bc04-11e7-8447-5c772ebfdda0.png)

Note that there is no mana in my mana pool here and I have only played Turn // Burn this turn.

Affects: [Icefall Regent]
 <img src="https://pennydreadfulmagic.com/image/Icefall%20Regent/" height="300px">

**Comment by stash86** [comment]
Still bugged

**Comment by stash86** [comment]
fixed as of today
