### ISSUE TITLE
If Vesuvan Shapeshifter copies a Megamorph creature with it's face-up ability, it will retain the Megamorph ability in later turns, gaining +1/+1 counters.

### ISSUE THREAD

**Issue by jmeka** [PennyDreadfulMTG/modo-bugs#220]
![capture](https://user-images.githubusercontent.com/28836887/32417856-9b9c283a-c22d-11e7-9f50-614a498541a1.JPG)

Affects: [Vesuvan Shapeshifter]
 <img src="https://pennydreadfulmagic.com/image/Vesuvan%20Shapeshifter/" height="300px">

**Comment by stash86** [comment]
Still bugged

**Comment by jmeka** [comment]
This is still bugged

**Comment by stash86** [comment]
Fixed according to https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-june-11-2019
