### ISSUE TITLE
[Reap] puts a "face down ability" into hand instead of the targetted cards

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#23]
Not sure if it's an always happens bug or only happens when there are more black permanents than legal targets
Affects: [Reap]
 <img src="https://api.scryfall.com/cards/named?exact=Reap&format=image" width="300px">

**Comment by silasary** [comment]
Confirmed

**Comment by silasary** [comment]
![image](https://user-images.githubusercontent.com/194254/28754587-b17c2996-758b-11e7-9b78-dbdca1224ecc.png)
Didn't quite restart the game...  But there is a face-down 'ability' in my hand.

**Comment by silasary** [comment]
![image](https://user-images.githubusercontent.com/194254/34361364-a4955f8e-eabd-11e7-907e-079de55e6a18.png)
Still bugged.

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ May 1st announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-may-01-2018).

> You can again continue to Reap the rewards of Reap.
