### ISSUE TITLE
[Pack's Disdain] does not work

### ISSUE THREAD

**Issue by nathanj** [PennyDreadfulMTG/modo-bugs#235]
Screenshot 1 right before playing the card
![Screenshot 1 right before playing the card](https://user-images.githubusercontent.com/6372/33920108-2a6b4496-df8a-11e7-8883-c36ae724790c.png)
Screenshot 2 after playing it. Heir to the Night is still alive and should have died.
![Screenshot 2 after playing it. Heir to the Night still alive and should have died.](https://user-images.githubusercontent.com/6372/33920139-5b20d90c-df8a-11e7-8f83-97962b37d741.png)
Affects: [Pack's Disdain]
 <img src="https://api.scryfall.com/cards/named?exact=Pack%27s%20Disdain&format=image" width="300px">

**Comment by BackAlleyG** [comment]
Fixed in build notes of [Jan 30 announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-january-30-2018)
