### ISSUE TITLE
Jodah's Avenger's activated ability doesn't work correctly.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#238]
Spotted by Saffron Olive: https://youtu.be/2JJoqRcjzVY?t=1h28m29s

**What is the actual behavior of the card?**
 - Keeps going until you say yes to "Double Strike." Otherwise, it pretty much just keeps shrinking and it continues asking you about different abilities. Only works properly if you only want to grant double-strike. If you find yourself "stuck," you can just keep pressing yes and you'll eventually get to where it you asks you about double strike again and then press yes. 

Affects: [Jodah's Avenger]
 <img src="https://pennydreadfulmagic.com/image/Jodah%27s%20Avenger/" height="300px">

**Comment by BackAlleyG** [comment]
This bug doesn't actually go on infinitely, just may seem like it if you don't get too far into it and don't know how to get out. Will pdate initial comment with more details and also title as well.

**Comment by stash86** [comment]
fixed
