### ISSUE TITLE
[Archangel of Strife] War or Peace choice repeats indefinitely.

### ISSUE THREAD

**Issue by Pseudodude** [PennyDreadfulMTG/modo-bugs#239]
Affects: [Archangel of Strife]
 <img src="https://api.scryfall.com/cards/named?exact=Archangel%20of%20Strife&format=image" width="300px">

**Comment by BackAlleyG** [comment]
Fixed in build notes of [Jan 30 announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-january-30-2018)
