### ISSUE TITLE
While on the stack, the triggered ability of Hanweir Garrison contains a text error that indicates an incorrect number of tokens to be added. This is a display issue only.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#242]
From bug blog.

Affects: [Hanweir Garrison]

 <img src="https://api.scryfall.com/cards/named?exact=Hanweir%20Garrison&format=image" width="300px">

**Comment by BackAlleyG** [comment]
This seems to have been fixed. Neither side's triggered attack ability is displaying an incorrect text error about the number of tokens to be created so closing it for now,

![image](https://user-images.githubusercontent.com/31076829/35657694-cbc3843a-06cb-11e8-9b58-93471a1089d6.png)

![image](https://user-images.githubusercontent.com/31076829/35658170-f2dc8c7c-06cd-11e8-9c50-534e40d96035.png)
