### ISSUE TITLE
Opponent is not given the option to scry card to the bottom when clashing

### ISSUE THREAD

**Issue by HypoSoc** [PennyDreadfulMTG/modo-bugs#243]
**What is the expected behaviour of the card?**
After clashing, both players should have the option to place the clashing card on the top or bottom of their library.

**What is the actual behaviour of the card?**
While the clash works as intended for the casting player, the opponent is not given the option where to put his/her revealed card. The card is left on top without giving a choice.

**Screenshot**
(Attach a screenshot or video here)

**Please provide a list of affected cards**
Affects: [Release the Ants] [Adder-Staff Boggart] [Bog Hoodlums] [Captivating Glance] [Fire Juggler] [Fistful of Force] [Gilt-Leaf Ambush] [Hoarder's Greed] [Lash Out] [Nath's Elite] [Oaken Brawler] [Paperfin Rascal] [Pulling Teeth] [Recross the Paths] [Redeem the Lost] [Research the Deep] [Revive the Fallen] [Ringskipper] [Scattering Stroke] [Sentry Oak] [Spring Cleaning] [Springjack Knight] [Titan's Revenge] [Weed Strangle] [Whirlpool Whelm] [Woodland Guidance]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Release%20the%20Ants&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Adder-Staff%20Boggart&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Bog%20Hoodlums&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Captivating%20Glance&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Fire%20Juggler&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Fistful%20of%20Force&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Gilt-Leaf%20Ambush&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Hoarder%27s%20Greed&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Lash%20Out&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Nath%27s%20Elite&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Oaken%20Brawler&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Paperfin%20Rascal&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Pulling%20Teeth&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Recross%20the%20Paths&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Redeem%20the%20Lost&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Research%20the%20Deep&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Revive%20the%20Fallen&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Ringskipper&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Scattering%20Stroke&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Sentry%20Oak&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Spring%20Cleaning&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Springjack%20Knight&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Titan%27s%20Revenge&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Weed%20Strangle&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Whirlpool%20Whelm&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Woodland%20Guidance&format=image" width="200px">

**Comment by stash86** [comment]
![clash 1](https://user-images.githubusercontent.com/13656154/34810456-d028f610-f6de-11e7-837f-813da7a0b562.png)

Only I (as the player casting the clash card) get the prompt window to choose whether I want to put it in the bottom. Opponent don't even get the pop-up window showing his/her card

**Comment by BackAlleyG** [comment]
Fixed in build notes of [March 13 announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-march-13-2018).

Also did some testing with clash cards to be sure they're working fine, including Release the ants, and they are indeed fixed.
