### ISSUE TITLE
If opponent choose to discard a card due to [Painful Quandary], he/she can't choose a card to discard, and the spell will resolves as normal

### ISSUE THREAD

**Issue by HypoSoc** [PennyDreadfulMTG/modo-bugs#244]
**What is the expected behaviour of the card?**
Opponents should be forced to pay life or discard a card whenever they cast a spell.
**What is the actual behaviour of the card?**
Opponent did not pay life and was not required to discard a card.
**Screenshot**
(Attach a screenshot or video here)

**Please provide a list of affected cards**
Affects: [Painful Quandary]
**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Painful%20Quandary&format=image" width="300px">

**Comment by stash86** [comment]
It's working

Opp's PoV
![quandary](https://user-images.githubusercontent.com/13656154/34810165-fa8b3d3e-f6dc-11e7-923f-35cdf0d98cce.PNG)

My PoV
![quandary 1](https://user-images.githubusercontent.com/13656154/34810068-90e4ed3a-f6dc-11e7-80e7-a11bb960454a.png)

**Comment by stash86** [comment]
Somehow it's bugged again. Opp don't have to discard

**Comment by BackAlleyG** [comment]
This seems to have been fixed. I tested it for a while with no occurrence of the bug.

![image](https://user-images.githubusercontent.com/31076829/37319090-04dff1f8-2644-11e8-8f40-551868782f1a.png)
![image](https://user-images.githubusercontent.com/31076829/37319101-1afa96a0-2644-11e8-97bc-adef2c8a0624.png)
