### ISSUE TITLE
The Scarab God and God-Pharaoh's Gift do not respect 706.9d and replaces characteristic defining abilities when creating copies of creatures.

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/modo-bugs#269]
**What is the expected behaviour of the card?**
For reference:
> 706.9d When applying a copy effect that doesn’t copy a certain characteristic, retains an original value for a certain characteristic, or modifies the final value of a certain characteristic, any characteristic-defining ability (see rule 604.3) of the object being copied that defines that characteristic is not copied. If that characteristic is color, any color indicator (see rule 204) of that object is also not copied. 
> 
> Example: Quicksilver Gargantuan is a creature that reads, “You may have Quicksilver Gargantuan enter the battlefield as a copy of any creature on the battlefield, except it’s still 7/7.” Quicksilver Gargantuan enters the battlefield as a copy of Tarmogoyf, which has a characteristic-defining ability that defines its power and toughness. Quicksilver Gargantuan does not have that ability. It will be 7/7. 

**What is the actual behaviour of the card?**
 - From the referenced rule, I'm assuming if it exiles something like a tarmogoyf , the token copy will be whatever the tarmogoyf would be instead of being a 4/4. 

**Screenshot**
![image](https://user-images.githubusercontent.com/31076829/34924065-20f0dc74-f96f-11e7-9bdf-c9d0c6513933.png)

Edit: Replaced old picture with a much more prettier picture where all the card images have loaded.

**Please provide a list of affected cards**
Affects: [The Scarab God]

**Card Images**

 <img src="https://pennydreadfulmagic.com/image/The%20Scarab%20God/" height="300px">
Bug Blog Text: [The Scarab God] does not respect 706.9d and replaces characteristic defining abilities when creating copies of creatures.

**Comment by BackAlleyG** [comment]
Just added a screenshot

**Comment by silasary** [comment]
Bug Blog Text: [The Scarab God] does not respect 706.9d and replaces characteristic defining abilities when creating copies of creatures.

**Comment by stash86** [comment]
God-Pharaoh's gift fixed. Doesn't have Scarab God to check it, so I'll remove gift only.

**Comment by stash86** [comment]
fixed

**Comment by MultiDragon** [comment]
Apparently [Offspring's Revenge] has the same problem now: https://www.youtube.com/watch?v=kyCelr7t6yA at 33:50
