### ISSUE TITLE
Thran Turbine mana is able to be used to cast spells

### ISSUE THREAD

**Issue by Swaskowi** [PennyDreadfulMTG/modo-bugs#279]
**What is the expected behaviour of the card?**
 - You should not be able to cast spells with the mana generated by Thran Turbine

**What is the actual behaviour of the card?**
 - You can cast spells using said mana.  

**Screenshot**
![image](https://user-images.githubusercontent.com/595670/35313557-0c900116-008f-11e8-9c38-1df8df6a52e7.png)
![image](https://user-images.githubusercontent.com/595670/35313569-20134126-008f-11e8-9127-811c3aeb0480.png)

**Please provide a list of affected cards**
Affects: [Thran Turbine] Possibly other mana sources that have restrictions of some type. 

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Thran%20Turbine/" height="300px">

**Comment by stash86** [comment]
fixed
