### ISSUE TITLE
Lavamancer's Skill the "T: deal 1 damage" ability does not let you choose a target

### ISSUE THREAD

**Issue by Pseudodude** [PennyDreadfulMTG/modo-bugs#289]
**What is the expected behaviour of the card?**
 - Any creature (wizard or not) enchanted by Lavamancer's Skill should be able to tap to ping a creature for 1 damage.

**What is the actual behaviour of the card?**
 - It's possible to try to activate the ping ability, but no creature can be chosen as a valid target.
 - The "T: deal 2 damage to target creature" ability granted to wizards functions as expected.
 - In addition, if a wizard is enchanted, only the "T: deal 1 damage" ability is shown in blue text in the enchanted creature's text box.

**Screenshot**
Abilities granted by Lavamancer's Skill:
![lavamancer s_skill_menu](https://user-images.githubusercontent.com/22277621/35494924-204184c8-0512-11e8-874d-8be073b85260.png)

Choosing target for (wizard) "T: deal 2 damage to target creature"
![lavamancer s_skill_wizard](https://user-images.githubusercontent.com/22277621/35494941-43f1a42a-0512-11e8-82a7-80ffd7446792.png)

Choosing target for "T: deal 1 damage to target creature"
![lavamancer s_skill_plebe](https://user-images.githubusercontent.com/22277621/35494926-28ddc010-0512-11e8-952b-88a03d32d23b.png)

**Please provide a list of affected cards**
Affects: [Lavamancer's Skill]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Lavamancer%27s%20Skill&format=image" width="300px">

**Comment by stash86** [comment]
Fixed according to [Nov 6th Build Notes](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-november-2018-11-06#build%20notes)
