### ISSUE TITLE
[Suffer the Past] Costs {2} more

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#29]

**Comment by silasary** [comment]
Still bugged.

**Comment by jmeka** [comment]
Still bugged:

https://www.youtube.com/watch?v=6ux1RliQBbQ

**Comment by silasary** [comment]
Thanks

**Comment by silasary** [comment]
Fixed in [July 11 build notes](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-july-11-2017#item8)
