### ISSUE TITLE
Sin Prodder's upkeep trigger damage isn't associated with Sin Prodder.

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/modo-bugs#296]
**What is the expected behaviour of the card?**
 - When Sin Prodder deals damage to a player, that damage should be preventable, reduced, or otherwise affectable.

**What is the actual behaviour of the card?**
 - The player takes damage as written, unmodified by cards such as Greater Realm of Preservation, Orbs of Warding, and Phyresis.

**Screenshot**
(Attach a screenshot or video here)

**Please provide a list of affected cards**
Affects: [Sin Prodder]
See Also: [Greater Realm of Preservation], [Orbs of Warding], [Temporal Isolation], [Prismatic Circle] and [Phyresis].

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Sin%20Prodder&format=image" width="300px">

**Comment by mmrsad** [comment]
Definitely a sin prodder issue :(   Prismatic circle also does not prevent the damage.  ![image](https://user-images.githubusercontent.com/35934185/40269157-5820fe70-5b37-11e8-9b64-c9ee48ff5168.png)

**Comment by jgabrielygalan** [comment]
@silasary and I tested it again on August 18th. It's working now. She used a Greater Realm of Preservation in response to the upkeep trigger, and the damage was correctly prevented.
