### ISSUE TITLE
[Undead Alchemist] Cards are milled as an additional effect, not as a replacement effect.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#30]

**Comment by jmeka** [comment]
![bugss1](https://cloud.githubusercontent.com/assets/28836887/26282124/b8e9dcea-3dd8-11e7-9c60-2fea418c8999.png)

I attacked myself and instead of damage, I milled 4 cards. Open Graveyard/Exile pile for extra proof.

**Comment by jmeka** [comment]
![bugss1](https://cloud.githubusercontent.com/assets/28836887/26282137/f97086f6-3dd8-11e7-8217-89f414ce056b.png)
Attacked myself in solitaire with Alchemist, got milled 4 and no damage. Graveyard/exile pile open for extra proof.
