### ISSUE TITLE
[Animate Dead] If you target an opponent's creature, it appears on your opponent's battlefield until the ETB effect resolves. 

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/modo-bugs#311]
**What is the expected behaviour of the card?**
 - works as expected

**What is the actual behaviour of the card?**
 - If you reanimate an opponent's creature, it appears on your opponent's side of the field  until the etb ability resolves

**Screenshot**
![image](https://user-images.githubusercontent.com/31076829/36569261-193ce2f2-17fb-11e8-9415-f336f1b3fe70.png)

![image](https://user-images.githubusercontent.com/31076829/36569624-88a4c7ee-17fc-11e8-81aa-59878ec4a01e.png)

**Please provide a list of affected cards**
Affects: [Animate Dead]

**Card Images**

**Comment by silasary** [comment]
This is intended.  When you first cast the card, it is enchanting a card in your opponent's graveyard.
As with all auras (in the Duel Scene - Multiplayer is a separate beast), if an aura is enchanting an object on your opponent's side of the field, it appears as close to that object as possible.

As such, Animate dead is doing exactly what it's meant to do.
