### ISSUE TITLE
Clone Legion puts multiple excess copies of all creatures from all of the targeted player's zones.

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#314]
**What is the expected behaviour of the card?**
 - Clone Legion put tokens that are copies of creatures from target player's battlefield

**What is the actual behaviour of the card?**
 - Clone Legion put tokens copies of creatures from all zones of targeted player's 75

This includes:
 - the sideboard (only 1 token per creature card) 
 - graveyard (tokens were created with all copies in the yard) 

Based on this reddit post https://www.reddit.com/r/MTGO/comments/8123ek/clone_legion_is_bugged_on_mtgo/

**Screenshot**
![image](https://user-images.githubusercontent.com/31076829/36881450-30bc9818-1d9c-11e8-9d2e-4f97fd165107.png)

**Please provide a list of affected cards**
Affects: [Clone Legion]

**Card Images**
 <img src="http://magic.bluebones.net/proxies/index2.php?c=Clone%20Legion" height="300px">

**Comment by BackAlleyG** [comment]
Screenshots and more info incoming

**Comment by Brefin** [comment]
[Clone Legion] will also copy every token creature you've had in game even if they're not on the battlefield when you cast [Clone Legion]

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ June 12th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-june-12-2018-2018-06-12).

>Clone Legion no longer clones the entire library.
