### ISSUE TITLE
The controller of the clash ability is not given the option to scry card to the bottom when clashing

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#317]
**What is the expected behaviour of the card?**
 - After clashing, both players should have the option to place the clashing card on the top or bottom of their library.

**What is the actual behaviour of the card?**
 - While the clash works as intended for the opponent, the casting player is not given the option where to put his/her revealed card. The card is left on top without giving a choice.

**Screenshot**
(Attach a screenshot or video here)

**Please provide a list of affected cards**
Affects: [Broken Ambitions], [Pollen Lullaby]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Broken%20Ambitions&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Pollen%20Lullaby&format=image" width="200px">

**Comment by BackAlleyG** [comment]
Fixed in build notes of [March 13 announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-march-13-2018).

See #243 also
