### ISSUE TITLE
Splice onto Arcane abilities are incorrectly affected by cost reduction effects that are supposed to affect spells only if there are two or more cost-reducting permanents

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#319]
**What is the expected behaviour of the card?**
 - Splice abilities cost can't be reduced by spell cost-reduction abilities such as Locket of Yesterdays or Goblin Electromancer

**What is the actual behaviour of the card?**
 - The cost for (x-1) splice abilities will be reduced if you control two or more cost-reducting permanents (don't have to have the same name), where x is the number of those permanents that the player control.
So for example, if I control 3 cost-reducting permanents, I can splice 2 arcane cards for cheap.
If I control 6 of those permanents, I can splice 5 arcane cards for cheap. Any extra spliced card(s) after those (x-1) slot will have to pay the full cost of the splice.

**Screenshot**
https://youtu.be/dWz2fOO0L1c
[Test on 2018-05-18 Take 1](https://youtu.be/YCHeIGlecgE)
[Test on 2018-05-18 Take 2](https://youtu.be/iWq4pCN2zl8)
[Better test on 2018-05-31 that shows the exact bug](https://youtu.be/oeMHaj1jNGA)

**Please provide a list of affected cards**
Affects: [Candles' Glow] [Consuming Vortex] [Dampen Thought] [Desperate Ritual] [Evermind] [Glacial Ray] [Goryo's Vengeance] [Hideous Laughter] [Lifted by Clouds] [Overblaze] [Reweave] [Shifting Borders] [Soulless Revival] [Strange Inversion] [Through the Breach] [Vital Surge] [Wear Away]

**Card Images**

 <img src="https://api.scryfall.com/cards/named?exact=Candles%27%20Glow&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Consuming%20Vortex&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Dampen%20Thought&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Desperate%20Ritual&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Evermind&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Glacial%20Ray&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Goryo%27s%20Vengeance&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Hideous%20Laughter&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Lifted%20by%20Clouds&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Overblaze&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Reweave&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Shifting%20Borders&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Soulless%20Revival&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Strange%20Inversion&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Through%20the%20Breach&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Vital%20Surge&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Wear%20Away&format=image" width="200px">

**Comment by silasary** [comment]
Can we please tag this bug on the splice cards, instead of all cost
reduction cards?

**Comment by stash86** [comment]
Affected cards updated into Splice cards

**Comment by BackAlleyG** [comment]
@stash86 would you mind testing this bug again when you get the chance? I assume this was fixed with the taxing effects bug was mention in a somewhat recent builds notes, but it didn't specifically mention cost-reduction effect so probably best to be certain. Thanks.

**Comment by stash86** [comment]
This one still bugged, and if you notice the title of the bug, now the bug don't required you to have 2 cost-reducting permanents with the same name. In my video, I have 2 such permanents with different name, and the splice got discounted

**Comment by stash86** [comment]
Removing splice cards that aren't affected by this bug (those that have single mana cost for the splice ability, or non-mana payment)

**Comment by stash86** [comment]
Still bugged. Add new video that shows the exact bug

**Comment by stash86** [comment]
So the real problem lies in how MTGO handles Splicing.

The correct behaviour are
1. Put the original spell on the stack
2. Announce any spell(s) that you want to splice into the original spell
3. Calculate total cost (cost of original spell plus the splicing cost of the spliced spell(s))
4. Apply any available cost increaser and reducer
5. Pay the cost
6. Priority move to your opponent

How MTGO handles it
1. Put the original spell on the stack
2. Pay the cost of the original spell
3. Announce 1 spell that you want to splice into the original spell
4. Pay the splice cost for that spliced card
5. If you want to add another splice card, go back to step 3
6. Priority move to your opponent

So no wonder why player get the wrong concept about splice ability
