### ISSUE TITLE
Cards that are only common in the PRM set can be added to Pauper decks, but you can't join a Pauper match with decks that have those cards

### ISSUE THREAD

**Issue by csuhta** [PennyDreadfulMTG/modo-bugs#322]
The following cards are commons in the PRM set and not commons elsewhere:

- [Zodiac Rooster](https://scryfall.com/card/prm/35082)
- ~~[Circle of Flame](https://scryfall.com/card/prm/41648)~~
- [Headless Horseman](https://scryfall.com/card/prm/35052)

You can add these cards to a Pauper deck in the MTGO deck editor, but if you try to begin a game with that deck you will receive a server error. We suspect that the deck editor and the server use different systems to determine Pauper legality.

These cards also match the criteria, but we were unable to obtain a copy to test with:

- ~~[Hada Freeblade](https://scryfall.com/card/prm/43558)~~
- [Aisling Leprechaun ](https://scryfall.com/card/prm/35050)
- [Zodiac Dog](https://scryfall.com/card/prm/35102)
- [Zodiac Goat](https://scryfall.com/card/prm/35098)
- [Zodiac Rabbit](https://scryfall.com/card/prm/35086)
- [Zodiac Rat](https://scryfall.com/card/prm/35094)
- [Zodiac Snake](https://scryfall.com/card/prm/35096)

More information/data:

https://docs.google.com/spreadsheets/d/19RNayAmcVslEfHWR0wcooGzyhnQVFnBR-vVWaQUhw74/edit?usp=sharing
Affects: [Zodiac Rooster] [Headless Horseman]
 <img src="https://pennydreadfulmagic.com/image/Zodiac%20Rooster|Headless%20Horseman/" height="300px">

**Comment by csuhta** [comment]
Headless Horseman also needs to be tested: https://scryfall.com/card/prm/35052

**Comment by silasary** [comment]
Horseman is aquirable, can be added to decks, but you can't start the game.

**Comment by csuhta** [comment]
<img width="396" alt="2qx6c9jrxa" src="https://user-images.githubusercontent.com/769083/37443136-8cd973ac-27e0-11e8-9446-c9755f8f09d8.png">

**Comment by csuhta** [comment]
Reported to WotC, Incident: 180315-000214

**Comment by csuhta** [comment]
This problem is also now happening with unreleased Battlebond cards, like Dwarven Lightsmith. This cards is in the MTGO data files, and you can see it in the deckbuilder as Pauper legal, but you cannot actually play a game with it.

**Comment by stash86** [comment]
fixed for now
