### ISSUE TITLE
Token created by Summoner's Bane have incorrect art and incorrectly display that they have flying

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/modo-bugs#326]
**Screenshot**
![image](https://user-images.githubusercontent.com/31076829/37264305-fa7e3c9a-2582-11e8-904f-2b933e0de317.png)

 - The tokens also have blue power & toughness text which normally indicates their pow/tou have been modified. Right clicking them shows a "(1/1)" as the "originally stats.
 - Not really sure where this art belonged to begin with but it's nice art nevertheless. 

**Please provide a list of affected cards**
Affects: [Summoner's Bane]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Summoner%27s%20Bane&format=image" width="300px">

**Comment by NARFNra** [comment]
Evidence seems to point to it being an old Meloku token (and he is the only card that creates 1/1 flying illusions)

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ June 5th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-june-05-2018-2018-06-05).

>The Illusion token from Summoner's Bane no longer displays that it has flying.
