### ISSUE TITLE
All creatures searched using Weird Harvest's ability will end in the hand of the last priority player

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#334]
**What is the expected behaviour of the card?**
 - Creatures searched using Weird Harvest's ability will ends up in their respective owners' hand

**What is the actual behaviour of the card?**
 - All the creature cards will ends up in the hand of the last priority player,which means
1. In a normal game, all the creatures will ends up in the opponent's hand
2. In a multiplayer game, all the creature will ends up in the farthest player in term of turn order

Reported [here](https://www.reddit.com/r/MTGO/comments/842wji/strange_bug_with_weird_harvest/)

**Screenshot**
![image](https://user-images.githubusercontent.com/13656154/37446962-ea23b392-2862-11e8-88f4-79cfc2490716.png)

**Please provide a list of affected cards**
Affects: [Weird Harvest]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Weird%20Harvest/" height="300px">

**Comment by silasary** [comment]
Confirmed for 3.4.102.2007 via https://youtu.be/lxGctupk7hw?t=1m

**Comment by bakert** [comment]
Confirmed again https://www.reddit.com/r/magicTCG/comments/9aubf0/i_searched_a_creature_with_weird_harvest_and_mtgo/

**Comment by stash86** [comment]
Fixed according to [Nov 13th Build Notes](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-november-13-2018-2018-11-13#Build%20Notes)
