### ISSUE TITLE
The calculation code seems to be wrong, because one third of three (3) is calculated as two (2)

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#335]
**What is the expected behaviour of the card?**
 - When x is 3, one third of it (rounded up) supposed to be 1. If x is 4, then the one third is 2

**What is the actual behaviour of the card?**
 - When x is 3, the one third is 2. Reported [here in reddit](https://www.reddit.com/r/magicTCG/comments/84o173/mtgo_floating_point_error/)
Additional ifo, this game was a Freeform Vanguard game, so it might or might not have effect in the bug [comment 1](https://www.reddit.com/r/magicTCG/comments/84o173/mtgo_floating_point_error/dvr1z6d/) [comment 2](https://www.reddit.com/r/magicTCG/comments/84o173/mtgo_floating_point_error/dvr1gns/)

**Screenshot**
![image](https://user-images.githubusercontent.com/13656154/37502769-184f86dc-2918-11e8-83f3-c91182e58481.png)

**Please provide a list of affected cards**
Affects: [Pox]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Pox/" height="300px">

**Comment by silasary** [comment]
Closing due to lack of followup.

**Comment by datrobino** [comment]
dont have a pox, but tested with dire fleet ravager on 3 life, which works correctly. This is either fixed, or the title is misleading and it is a pox specific bug.
