### ISSUE TITLE
Eldrazi Spawn and Scions created by cards from the Battle for Zendikar and Rise of the Eldrazi sets display "Add {1} to your mana pool" instead of "Add {C} to your mana pool"

### ISSUE THREAD

**Issue by BackAlleyG** [PennyDreadfulMTG/modo-bugs#339]
**Screenshot**
![image](https://user-images.githubusercontent.com/31076829/37610991-87f36ed4-2b77-11e8-84f8-022914a0c139.png)
![image](https://user-images.githubusercontent.com/31076829/37611795-c1050be0-2b79-11e8-9e00-a04ce4dedd4b.png)

Affects: [Eldrazi Spawn]
Bug Blog Text: [Eldrazi Spawn] and Scions created by cards from the Battle for Zendikar and Rise of the Eldrazi sets display "Add {1} to your mana pool" instead of "Add {C} to your mana pool" upon zoom. As this change in template was not a functional change, these tokens continue to function correctly.
 <img src="https://pennydreadfulmagic.com/image/Eldrazi%20Spawn/" height="300px">

**Comment by stash86** [comment]
they have kinda fix this by adding blue ability text on top of the black ability text, so assume this is fixed

![image](https://user-images.githubusercontent.com/13656154/83344991-e39e5a00-a348-11ea-843c-faf6bf593974.png)
