### ISSUE TITLE
Primitive Justice will either not cast/restart the game with a single target.

### ISSUE THREAD

**Issue by Kazaxat** [PennyDreadfulMTG/modo-bugs#36]
If you attempt to cast it with mana already floating it will tell you to choose a target, but then not actually cast when you've selected the target (won't use the mana either, just resets as though you hadn't done anything). If instead you choose the target THEN attempt to pay for it it will seem to leave the 2nd mana in your pool instead of applying towards the colorless cost. If you click that mana in the pool to try to use it, the game will freeze, then completely restart.

Oddly, if you have more than 1 target Primitive Justice appears to work fine. 

![capture](https://cloud.githubusercontent.com/assets/28510571/25783122/7f848c2a-3324-11e7-8519-351a9e4e1204.JPG)

Affects: [Primitive Justice]
 <img src="https://pennydreadfulmagic.com/image/Primitive%20Justice/" height="300px">

**Comment by silasary** [comment]
Well that's odd.

**Comment by stash86** [comment]
Still bugged

**Comment by stash86** [comment]
fixed
