### ISSUE TITLE
[Vastwood Hydra] allows you to place extra counters when it dies

### ISSUE THREAD

**Issue by truehero17** [PennyDreadfulMTG/modo-bugs#37]
The bug was that Vastwood hydra, wouldn't stop putting the counters from its death, onto another creature, even going beyond the counters that were on Vastwood hydra

**Comment by silasary** [comment]
![image](https://cloud.githubusercontent.com/assets/194254/25879021/4a49c85e-3572-11e7-9130-6f9710329b7f.png)
![image](https://cloud.githubusercontent.com/assets/194254/25879030/58a042fc-3572-11e7-99eb-dedf6b796b9f.png)

**Comment by truehero17** [comment]
Ok, so I wasn't crazy, thanks Silasary

**Comment by silasary** [comment]
Yeah, it's definitely a weird one.

**Comment by silasary** [comment]
This appears to be fixed
