### ISSUE TITLE
Exiled cards appear to come from opponents library.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#383]
From Bug Blog.
Affects:
See Also: [Bomat Courier], [Windbrisk Heights]

Bug Blog Text: Cards exiled by the triggered abilities of a number of cards which exile a card from their controller's library appear to be coming from the opponent's library instead. This affects cards such as [Bomat Courier], [Windbrisk Heights], and other similar cards. This is a display issue only.
 <img src="https://pennydreadfulmagic.com/image/Bomat%20Courier|Windbrisk%20Heights/" height="300px">

**Comment by datrobino** [comment]
ok fixed
