### ISSUE TITLE
Emerge spells cast for their emerge cost do not allow players to undo the creature sacrifice selection. Players may cancel and recast the spell to sacrifice a different creature.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#389]
From Bug Blog.
Affects: 

Bug Blog Text: Emerge spells cast for their emerge cost do not allow players to undo the creature sacrifice selection. Players may cancel and recast the spell to sacrifice a different creature.

**Comment by BackAlleyG** [comment]
This has been fixed
