### ISSUE TITLE
Nebuchadnezzar ability makes the game start endlessly repeating itself

### ISSUE THREAD

**Issue by Shantu58** [PennyDreadfulMTG/modo-bugs#39]
In both cases this happened to me I had X=opponent's hand size in a Commander game. Name selection seems fine, it bugs after that.

EDIT:

Affects: [Nebuchadnezzar]

 <img src="https://pennydreadfulmagic.com/image/Nebuchadnezzar/" height="300px">

**Comment by datrobino** [comment]
fixed
