### ISSUE TITLE
Creatures that enter the battlefield with counters based on the number of creatures in the graveyard (for example, Undergrowth Scavenger) do not count themselves if they are put onto the battlefield directly from the graveyard.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#395]
From Bug Blog.
Affects: [Undergrowth Scavenger]

Bug Blog Text: Creatures that enter the battlefield with counters based on the number of creatures in the graveyard (for example, [Undergrowth Scavenger]) do not count themselves if they are put onto the battlefield directly from the graveyard.
 <img src="https://pennydreadfulmagic.com/image/Undergrowth%20Scavenger/" height="300px">

**Comment by stash86** [comment]
fixed
