### ISSUE TITLE
If a token creature stops being blocked (e.g. all blocking creatures were destroyed), it will return to a pile with other unblocked identical tokens if any are present. Once there, the game log is the only way to identify which creature was blocked. To identify this creature, players can point their cursor to the name of the token in the game log entry that identifies the attacking creatures and locate the creature that no longer has a blocking creature associated with it.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#396]
From Bug Blog.
Affects: 

Bug Blog Text: If a token creature stops being blocked (perhaps because all blocking creatures were destroyed), it will return to a pile with other identical tokens if any are present. Once there, the game log is the only way to identify which creature was blocked. To identify this creature, players can point their cursor to the name of the token in the game log entry that identifies the attacking creatures and locate the creature that no longer has a blocking creature associated with it.

**Comment by datrobino** [comment]
fixed
