### ISSUE TITLE
Odric, Lunarch Marshal's triggered ability ignores the hexproof ability on a creature if it only has it temporarily.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#398]
From Bug Blog.
Affects: [Odric, Lunarch Marshal]

Bug Blog Text: [Odric, Lunarch Marshal]'s triggered ability ignores the hexproof ability on a creature if it only has it temporarily.
 <img src="https://pennydreadfulmagic.com/image/Odric%2C%20Lunarch%20Marshal/" height="300px">

**Comment by stash86** [comment]
Fixed

![image](https://user-images.githubusercontent.com/13656154/80485707-ddf1d500-8994-11ea-94b9-93c506fe6fa6.png)
