### ISSUE TITLE
When some cards with madness are discarded, the triggered ability does not display the madness cost while on the stack. Players can find this information by right-clicking the card or by viewing the game log.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#399]
From Bug Blog.
Affects: 

Bug Blog Text: When some cards with madness are discarded, the triggered ability does not display the madness cost while on the stack. Players can find this information by right-clicking the card or by viewing the game log.

**Comment by datrobino** [comment]
i think this one is fixed, either way it doesnt actually impact the game at all
