### ISSUE TITLE
Some specific protections (Snow or specificially spectra ward) are not counted as protections to be gained or shared

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#4]
From spreadsheet

Affects: [Cairn Wanderer]

 <img src="https://pennydreadfulmagic.com/image/Cairn%20Wanderer/" height="300px">

**Comment by NARFNra** [comment]
It seems that while some protections are not written on the card many of them are still functional. I am commenting here about this despite having another open ticket regarding the graphical bug because the issue specifically noted here (Harbinger of Spring) seems to be a graphical bug where the protection still functions. 

Please observe: Fanatical Firebrand cannot target anything on the field after the Concerted Effort trigger, even though the card text does not appear to change.

![concerted_effort_harbinger](https://user-images.githubusercontent.com/7265358/37267804-83e10c94-2590-11e8-99d4-9d55bed44e71.png)

**Comment by NARFNra** [comment]
So far, the protection from all colors granted by Spectra Ward appears to be the only protection I've seen so far that Concerted Effort fails to FUNCTIONALLY grant as well as visibly grant. Protection from all colors is visible and functional if granted with Concerted Effort from Pristine Archangel...

![image](https://user-images.githubusercontent.com/7265358/37267914-23925e28-2591-11e8-9630-491382bcdcc7.png)

And protections granted by auras work fine with Concerted Effort, as we can see from Holy Mantle's "protection from creatures"...

![image](https://user-images.githubusercontent.com/7265358/37267913-1f9fd19c-2591-11e8-934f-f6d672f4bdbc.png)

But Spectra Ward does not seem to grant its protection from all colors to any other creature. Fan Bearer can tap Firebrand here.

![image](https://user-images.githubusercontent.com/7265358/37268066-fc985362-2591-11e8-9cc1-0e967b9c3927.png)

**Comment by BackAlleyG** [comment]
Have done some further testing and so far it seems this happens only for spectra. Have tested other similar auras with "this effect doesn't remove ~" auras but there aren't any other auras with "this effect doesn't remove auras" so may be confined to spectra ward. Still testing some specific protections and working on compiling a list of protections and whether or not they need testing yet or have been and aren't bugged.

**Comment by BackAlleyG** [comment]
Okay so seem that the only protections that aren't shareable are pro snow and protection specifically from spectra ward. Everything else I've tested has worked. See #327 's initial comment for my short untested list 

pro snow not being shared.
![image](https://user-images.githubusercontent.com/31076829/37447613-4127f67c-27f9-11e8-9e8b-d92ad32cd3b1.png)

Also found out the same is true for cairn wander and death-mask duplicant  (see below) so updating post and will try to figure out a good general title

![image](https://user-images.githubusercontent.com/31076829/37447799-1710d3bc-27fa-11e8-865a-0edfcd15ba33.png)
![image](https://user-images.githubusercontent.com/31076829/37447828-346b0554-27fa-11e8-94a6-26d224f34a9c.png)

**Comment by stash86** [comment]
Still bugged

**Comment by stash86** [comment]
Still bugged

**Comment by stash86** [comment]
Good news. Only cairn wanderer still bugged

![image](https://user-images.githubusercontent.com/13656154/109366039-c4335e00-78d5-11eb-8632-fcf28adc8bd0.png)

**Comment by stash86** [comment]
Closing this and opening a new bug issue for cairn wanderer
