### ISSUE TITLE
Abilities that trigger from a permanent becoming the target of a spell or ability (such as that of Silverfur Partisan) are not triggered by copies of spells automatically put onto the stack. For example: if a player controls Zada, Hedron Grinder and casts a spell on Zada, when Zada's triggered ability resolves, the player will be prompted to choose targets for the copies made by Zada. If the player chooses targets for the copies individually, Silverfur Partisan's ability will trigger correctly. If the player clicks OK to automatically choose the targets, the Partisan's ability won't trigger.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#400]
From Bug Blog.
Affects: [Silverfur Partisan], [Zada, Hedron Grinder], [Silverfur Partisan]

Bug Blog Text: Abilities that trigger from a permanent becoming the target of a spell or ability (such as that of [Silverfur Partisan]) are not triggered by copies of spells automatically put onto the stack. For example: if a player controls [Zada, Hedron Grinder] and casts a spell on Zada, when Zada's triggered ability resolves, the player will be prompted to choose targets for the copies made by Zada. If the player chooses targets for the copies individually, [Silverfur Partisan]'s ability will trigger correctly. If the player clicks OK to automatically choose the targets, the Partisan's ability won't trigger.
 <img src="https://pennydreadfulmagic.com/image/Silverfur%20Partisan|Zada%2C%20Hedron%20Grinder|Silverfur%20Partisan/" height="300px">

**Comment by stash86** [comment]
fixed
