### ISSUE TITLE
Ever After resolves immediately upon selection of the second target instead of allowing the player to click a "Done" button.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#404]
From Bug Blog.
Affects: [Ever After]

Bug Blog Text: [Ever After] resolves immediately upon selection of the second target instead of allowing the player to click a "Done" button.
 <img src="https://pennydreadfulmagic.com/image/Ever%20After/" height="300px">

**Comment by stash86** [comment]
After the player select second target, the system moves on to "pay the cost" step. If the is any mistake in the target, the player can click "Cancel" and redo the whole process.
