### ISSUE TITLE
Narset, Enlightened Master's triggered ability does not allow players to cast split spells (such as Fire // Ice).

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#405]
From Bug Blog.
Affects: 

Bug Blog Text: [Narset, Enlightened Master]'s triggered ability does not allow players to cast split spells (such as [Fire // Ice]).

**Comment by BackAlleyG** [comment]
This has been fixed 

![image](https://user-images.githubusercontent.com/31076829/39482163-f2d0da76-4d3b-11e8-999f-2990c72a91ba.png)
