### ISSUE TITLE
When a player casts Kozilek, the Great Distortion, its triggered ability incorrectly triggers if the casting player has seven or more cards in hand. Upon resolution, the player will not draw cards if he or she already has seven or more cards in hand.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#408]
From Bug Blog.
Affects: [Kozilek, the Great Distortion]

Bug Blog Text: When a player casts [Kozilek, the Great Distortion], its triggered ability incorrectly triggers if the casting player has seven or more cards in hand. Upon resolution, the player will not draw cards if he or she already has seven or more cards in hand.
 <img src="https://pennydreadfulmagic.com/image/Kozilek%2C%20the%20Great%20Distortion/" height="300px">

**Comment by stash86** [comment]
fixed
