### ISSUE TITLE
If a permanent enters the battlefield as a copy of a permanent that had a choice made as it entered (such as Door of Destinies or Painter's Servant), the copy correctly allows the controller to make a new choice, but the abilities of the copy that refer to that choice do not function correctly.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#416]
From Bug Blog.
Affects: [Door of Destinies], [Painter's Servant]

Bug Blog Text: If a permanent enters the battlefield as a copy of a permanent that had a choice made as it entered (such as [Door of Destinies] or [Painter's Servant]), the copy correctly allows the controller to make a new choice, but the abilities of the copy that refer to that choice do not function correctly.
 <img src="https://pennydreadfulmagic.com/image/Door%20of%20Destinies|Painter%27s%20Servant/" height="300px">

**Comment by stash86** [comment]
working as intended
