### ISSUE TITLE
If a player attempts to sacrifice a pile of Eldrazi babies (Scions or Spawn) at once, only one of those tokens will be sacrificed.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#417]
From Bug Blog.
Affects: 

Bug Blog Text: If a player attempts to sacrifice a pile of Eldrazi babies (Scions or Spawn) at once, only one of those tokens will be sacrificed.

**Comment by stash86** [comment]
MTGO has change the system so you can't sacrifice the babies at once. You need to manually sac them one-by-one. There is no more "All of these cards:" choice
