### ISSUE TITLE
If a creature enters the battlefield and then gains haste, it no longer indicates that it entered the battlefield that turn.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#418]
From Bug Blog.
Affects: 

Bug Blog Text: If a creature enters the battlefield and then gains haste, it no longer indicates that it entered the battlefield that turn.

**Comment by stash86** [comment]
The only relevant visual indicator that currently exist is "Summoning sickness" indicator. So gaining haste definitely removes summoning sickness, which means the creature won't have the indicator anymore. If the creature lose the haste ability in the same turn, the "Summoning sickness" indicator would be visible again. Unless I miss a "entered the battlefield this turn" indicator, which I never see.
