### ISSUE TITLE
When a double-faced creature is copied by a non-token creature, the copy is incorrectly resistant to effects that would turn it face down, such asIxidron's triggered ability. Only double-faced cards cannot be turned face down.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#420]
From Bug Blog.
Affects: 

Bug Blog Text: When a double-faced creature is copied by a non-token creature, the copy is incorrectly resistant to effects that would turn it face down, such asIxidron's triggered ability. Only double-faced cards cannot be turned face down.

**Comment by stash86** [comment]
fixed
