### ISSUE TITLE
The Search Tool is not present in the Other Products tab of a trade

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#421]
From Bug Blog.
Affects: 

Bug Blog Text: The Search Tool is not present in the Other Products tab of a trade

**Comment by silasary** [comment]
It is technically a bug, as you can't fill Vanguards from a Freeform Vanguard deck without it.

**Comment by datrobino** [comment]
im just going to say this isnt a bug and is instead bad game design.
