### ISSUE TITLE
When face-down cards are given an activated ability, the art displays incorrectly on the stack when that ability is activated.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#427]
From Bug Blog.
Affects: 

Bug Blog Text: When face-down cards are given an activated ability, the art displays incorrectly on the stack when that ability is activated.

**Comment by BackAlleyG** [comment]
I tried this and it seems like the trigger art is correct so I'll close this for now. Should it not be the picture of a morph "token"? If anybody finds out anything different or new we can reopen.

![image](https://user-images.githubusercontent.com/31076829/39499170-5669cdca-4d7a-11e8-9a43-804cbb128bbc.png)
