### ISSUE TITLE
When casting a spell, if there is any mana already in the player's pool, the most recently produced colored mana is automatically applied to the spell first. For example, if a player taps a Cavern of Souls (naming Human), then an Island, then casts Delver of Secrets, the blue mana applied to the Delver's mana cost will be that from the Island. If the player tapped the Island, then the Cavern, the Cavern's mana would be applied to the spell, and it would be appropriately uncounterable.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#428]
From Bug Blog.
Affects: [Cavern of Souls]
Bug Blog Text: When casting a spell, if there is any mana already in the player's pool, the most recently produced colored mana is automatically applied to the spell first. For example, if a player taps a [Cavern of Souls] (naming Human), then an Island, then casts [Delver of Secrets], the blue mana applied to the Delver's mana cost will be that from the Island. If the player tapped the Island, then the Cavern, the Cavern's mana would be applied to the spell, and it would be appropriately uncounterable.
 <img src="https://pennydreadfulmagic.com/image/Cavern%20of%20Souls/" height="300px">

**Comment by silasary** [comment]
Oh god, that text is gross and excessively long

**Comment by stash86** [comment]
fixed
