### ISSUE TITLE
If a player makes a selection, then reverses that selection with the "undo" keyboard shortcut (default: CTRL+Z), the game log will sometimes incorrectly show both cards the player selected. Notably, this includes Oath of Nissa and similar effects that ask a player to put one of a small number of cards into their hand.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#430]
From Bug Blog.
Affects: [Oath of Nissa]

Bug Blog Text: If a player makes a selection, then reverses that selection with the "undo" keyboard shortcut (default: CTRL+Z), the game log will sometimes incorrectly show both cards the player selected. Notably, this includes [Oath of Nissa] and similar effects that ask a player to put one of a small number of cards into their hand.
 <img src="https://pennydreadfulmagic.com/image/Oath%20of%20Nissa/" height="300px">

**Comment by stash86** [comment]
They kinda fixed this by disabling the confirmation step, which means once you select a card, the game will move on, so there is no window to reverses the selection
