### ISSUE TITLE
Kamigawa Flip cards such as Stabwhisker the Odious are displayed as enchantments and do not respect the attack with all function or changes to power and toughness. Workaround: Click the creature separately to attack with it, and right click the creature to display its correct power and toughness.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#437]
From Bug Blog.
Affects: 

Bug Blog Text: Kamigawa Flip cards such as [Stabwhisker the Odious] are displayed as enchantments and do not respect the attack with all function or changes to power and toughness. Workaround: Click the creature separately to attack with it, and right click the creature to display its correct power and toughness.

**Comment by BackAlleyG** [comment]
Duplicate of #259
