### ISSUE TITLE
Dubious Challenge resets the game when played

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#456]
Found and confirmed on Reddit.
https://www.reddit.com/r/magicTCG/comments/8dlkdr/mtgo_dubious_challenge_glitch/
Affects: [Dubious Challenge]
 <img src="https://api.scryfall.com/cards/named?exact=Dubious%20Challenge&format=image" width="300px">

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ May 15th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-may-15-2018).

> Dubious Challenge can no longer dubiously reset the game.
