### ISSUE TITLE
Gideon of the Trials' emblem fails to prevent the opponent from winning the game via Approach of the Second Sun

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#457]
**What is the expected behaviour of the card?**
 - If you cast your second Approach of the Second Sun while your opponent control Gideon of the Trials and its emblem, the game will continue as if nothing happens.

**What is the actual behaviour of the card?**
 - Approach of the Second Sun still wins the game, despite the fact you control a Gideon.

**Screenshot**
First reported in [this reddit post](https://www.reddit.com/r/MTGO/comments/8dj3ie/bug/).
Video of this bug can be found in the final match of this mtggoldfish video. https://youtu.be/43QiMpTYLtQ?t=50m30s

**Please provide a list of affected cards**
Affects: [Gideon of the Trials]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Gideon%20of%20the%20Trials&format=image" width="300px">

**Comment by Rowsol** [comment]
![2018-04-22_152636](https://user-images.githubusercontent.com/35880360/39099043-957cacac-4641-11e8-819b-1ede0b4ffcd7.jpg)
Not sure how helpful this is but it's something.  With angel in play I couldn't lose to damage.  I casted the approach again and didn't win or lose.  I have no friends on here so I can't test in an actual game.

**Comment by stash86** [comment]
@Rowsol add me on mtgo, my ID is stash86. I'll help you test this bug. Create the deck in Freeform format

**Comment by stash86** [comment]
So Platinum Angel interacts correctly with Approach, which makes me wonder wether Gideon is the one bugged. I'll change the description and affected card for now, and hopefully someone who have Gideon can help us test it

**Comment by Rowsol** [comment]
This bug does indeed exist as shown here.  https://youtu.be/43QiMpTYLtQ?t=50m30s

**Comment by silasary** [comment]
I was literally about to post that video 😂

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ May 15th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-may-15-2018).

>Gideon of the Trial’s emblem now correctly prevents players from winning with “You win the game” effects such as Approach of the Second Sun.
