### ISSUE TITLE
Teferi’s Realm forces you to phase everything out

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#467]
**What is the expected behaviour of the card?**
 - At the beginning of each players’ upkeep, they choose which type of permanents to be phased out

**What is the actual behaviour of the card?**
 - The player must phasing out all permanents they control (reported in a discord, so need confirmation)

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Teferi's Realm]

**Card Images**
 <img src="http://magic.bluebones.net/proxies/index2.php?c=Teferi%27s%20Realm" height="300px">

**Comment by silasary** [comment]
Closing due to lack of followup.

**Comment by stash86** [comment]
fixed
