### ISSUE TITLE
Kamigawa Patron cycle's "Offering" cannot be canceled after sacrificing a creature

### ISSUE THREAD

**Issue by ElectricTuba** [PennyDreadfulMTG/modo-bugs#469]
**What is the expected behaviour of the card?**
 - After choosing a creature to sacrifice, you should be able to cancel paying for the Patron.

**What is the actual behaviour of the card?**
 - You cannot cancel trying to cast a Patron after choosing a creature to sacrifice. Pressing cancel will not reverse attempting to cast Patron and if you cannot generate enough mana, there is no way to escape trying to pay without conceding or timing out.

**Screenshot**
["Stuck" state](https://imgur.com/a/l6oc4pv)

**Please provide a list of affected cards**
Affects: [Patron of the Orochi], [Patron of the Kitsune], [Patron of the Moon], [Patron of the Akki], [Patron of the Nezumi]

**Card Images**

**Comment by Rowsol** [comment]
https://youtu.be/ps-ix84bSXo
Emerge works fine.  Not sure what eldrazi babies are.  Also, not sure how a screenshot can prove this bug.

**Comment by BackAlleyG** [comment]
Fixed in build notes of [May 1st announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-may-01-2018).

>  Cards with offering, such as Patron of the Kitsune, have had various issues with them fixed.

Double checked and both offering mechanic and eldrazi scions and spawns work.
