### ISSUE TITLE
Tocatli Honor Guard doesn't prevent Burning Tree Emissary

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#487]
**What is the expected behaviour of the card?**
 - Tocatli Honor Guard prevents all ETB abilities

**What is the actual behaviour of the card?**
 - You can still get mana out of Burning-Tree.

**Screenshot**
https://cdn.discordapp.com/attachments/436712104649818112/444285593040715779/Screenshot_3.png

**Please provide a list of affected cards**
Affects: [Tocatli Honor Guard]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Tocatli%20Honor%20Guard&format=image" width="300px">

**Comment by Rowsol** [comment]
![capture](https://user-images.githubusercontent.com/35880360/39923934-ca8b3c54-54f3-11e8-8af0-904770418b22.JPG)

It works fine for me.

**Comment by silasary** [comment]
Can we get a multiplayer test?

**Comment by Rowsol** [comment]
Who reported this?  The screenshot clearly shows the emissary being cast before the honor guard.

**Comment by stash86** [comment]
Closed because the player misremember the game sequence
