### ISSUE TITLE
Dust Elemental only returns two creatures if its controller only controls exactly three creatures (including Dust Elemental itself)

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#488]
**What is the expected behaviour of the card?**
 - When Dust Elemental enters the battlefield, return three creatures you control to their owner’s hand.

**What is the actual behaviour of the card?**
 - Dust Elemental only returns two creatures if its controller only controls exactly three creatures (including Dust Elemental itself)

**Screenshot**
![image](https://user-images.githubusercontent.com/194254/39952920-0ef762be-55e4-11e8-92cd-6b0350a2330a.png)

**Video**
[Test on 20180602](https://youtu.be/gNoIvovQVCE)

**Please provide a list of affected cards**
Affects: [Dust Elemental]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Dust%20Elemental/" height="300px">

**Comment by Pixywing** [comment]
The bug only seems to occur when you have exactly three creatures in play (two creatures are returned instead of three). Otherwise the card behaves as normal, makeshift mannequin seems to have zero effect on the number of creatures returned with Dust Elemental.

**Comment by Rowsol** [comment]
Why is a video needed?  The log shows what is returned.

**Comment by stash86** [comment]
Still bugged. Uploading video rn

**Comment by stash86** [comment]
Fixed as of today
