### ISSUE TITLE
Teferi, Hero of Dominaria's emblem can target Hexproof creatures

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#490]
**What is the expected behaviour of the card?**
 - Its emblem can't target hexproof creatures

**What is the actual behaviour of the card?**
 - According to [this post](https://www.reddit.com/r/MTGO/comments/8jsvlg/teferi_emblem_working_on_hexproof_bug/), the emblem can target Carnage Tyrant

**Screenshot**
(Attach a screenshot or video here)

**Please provide a list of affected cards**
Affects: [Teferi, Hero of Dominaria]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Teferi%2C%20Hero%20of%20Dominaria&format=image" width="300px">

**Comment by Spencerbot15** [comment]
If it ever did exist, it has been fixed since then. https://youtu.be/9ESKmEMxxDc?t=1h34m14s
