### ISSUE TITLE
Holistic Wisdom restarts the game when you activate it

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#531]
**What is the expected behaviour of the card?**
 - You return target card from your graveyard.

**What is the actual behaviour of the card?**
 - Game resets, loops twice, and resets.

**Screenshot**
![image](https://user-images.githubusercontent.com/194254/40662983-1535f91e-639b-11e8-8db3-06bebb2b8dd3.png)

**Please provide a list of affected cards**
Affects: [Holistic Wisdom]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Holistic%20Wisdom/" height="300px">

**Comment by bakert** [comment]
Reconfirmed by syu_tei.

**Comment by bakert** [comment]
Still bugged as of yesterday according to xbolthebirdx

**Comment by Rowsol** [comment]
fixed 
https://www.mtgo.com/news/mtgo-blog-6132023
