### ISSUE TITLE
Spells and non-static abilities that cares whether or not a permanent is enchanted, will see equipped permanent as enchanted

### ISSUE THREAD

**Issue by jgabrielygalan** [PennyDreadfulMTG/modo-bugs#532]
**What is the expected behaviour of the card?**
 - Equipped isn't the same as Enchanted

**What is the actual behaviour of the card?**
 - The system will see equipped permanents as enchanted. This issue for disadvantageous bugged cards

**Screenshot**
![brainspoil_bug](https://user-images.githubusercontent.com/247560/41111464-540baad4-6a7c-11e8-9ff7-76f9a30ef0b1.PNG)
[2018-06-13 part 1](https://youtu.be/UnhUsWP2Lk4)
[2018-06-13 part 2](https://youtu.be/d7aH9j3iJOk)

**Please provide a list of affected cards**
Affects: [Brainspoil][Time Elemental]

**Card Images**
 <img src="https://api.scryfall.com/cards/named?exact=Brainspoil&format=image" width="200px"><img src="https://api.scryfall.com/cards/named?exact=Time%20Elemental&format=image" width="200px">

**Comment by stash86** [comment]
Change the description and affected cards. Add videos for it

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ July 10th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-july-10-2018-2018-07-10).

>Brainspoil no longer considers an Equipment to be an enchantment.
