### ISSUE TITLE
Arena doesn't cause the creatures to fight

### ISSUE THREAD

**Issue by zinnerzPT** [PennyDreadfulMTG/modo-bugs#537]
**What is the expected behaviour of the card?**
 - The chosen creatures are tapped and then fight.

**What is the actual behaviour of the card?**
 - The chosen creatures are tapped.

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Arena]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Arena/" height="300px">

**Comment by silasary** [comment]
This bug was [mentioned on reddit](https://www.reddit.com/r/MTGO/comments/8thiop/debugging_bugged_cards/) by /u/Mitthrawnuruodo3113

**Comment by silasary** [comment]
Arena isn't actually listed on the bug blog. (Only Magus of)

**Comment by jmeka** [comment]
This is working as intended.
