### ISSUE TITLE
The activated ability of Sunforger does not shuffle the library.

### ISSUE THREAD

**Issue by Rowsol** [PennyDreadfulMTG/modo-bugs#540]
**What is the expected behaviour of the card?**
 - You need to shuffle your library at the end of the ability's resolution

**What is the actual behaviour of the card?**
 - Your library isn't shuffled

https://magic.wizards.com/en/articles/archive/magic-online/magic-online-bug-blog-june-28-2018-2018-06-28

**Screenshot**
https://www.youtube.com/watch?v=sWg9stZdMCM

**Please provide a list of affected cards**
Affects: [Sunforger]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Sunforger/" height="300px">

Bug Blog Text: The activated ability of [Sunforger] does not shuffle the library.

**Comment by silasary** [comment]
This bug has been removed from the bug blog!
