### ISSUE TITLE
Casting split cards Fused restarts the game in a buggy state

### ISSUE THREAD

**Issue by Error2105** [PennyDreadfulMTG/modo-bugs#543]
**What is the expected behaviour of the card?**
 - Flesh // Blood was fused, targeting a Korsan Tuskar (6/5) in my graveyard, my Spellbreaker behemoth (5/5) twice and the opponent. This should have resulted in Spellbreaker Behemoth dealing 11 damage to my opponent. 

**What is the actual behaviour of the card?**
 - Without resolving, the game reset and replayed everything up to the point of Flesh // Blood being cast. This repeated a few time before declaring the game a draw and starting a second game. During the second game, There were numerous visual bugs, several of which were game breaking. This included two of my opponents creatures being invisible, my graveyard appearing empty, being able to somehow block a creature in my hand, and the Blood side of Flesh // Blood vanishing (only Flesh was shown in hand). 

**Screenshot**
https://youtu.be/Fa7jsboljr0
https://youtu.be/7wcKa8WU6x0 (did some further testing to see if Spellbreaker Behemoth or Korsan Tuskar caused the bug, they didn't)

**Please provide a list of affected cards**
Affects: [Alive // Well], [Armed // Dangerous], [Beck // Call], [Catch // Release], [Down // Dirty], [Far // Away], [Flesh // Blood], [Give // Take], [Profit // Loss], [Ready // Willing], [Toil // Trouble], [Turn // Burn], [Breaking // Entering], [Protect // Serve], [Wear // Tear]

**Card Images**
 <img src="http://magic.bluebones.net/proxies/index2.php?c=Alive%20//%20Well|Armed%20//%20Dangerous|Beck%20//%20Call|Catch%20//%20Release" height="300px"><img src="http://magic.bluebones.net/proxies/index2.php?c=Down%20//%20Dirty|Far%20//%20Away|Flesh%20//%20Blood|Give%20//%20Take" height="300px"><img src="http://magic.bluebones.net/proxies/index2.php?c=Profit%20//%20Loss|Ready%20//%20Willing|Toil%20//%20Trouble|Turn%20//%20Burn" height="300px"><img src="http://magic.bluebones.net/proxies/index2.php?c=Breaking%20//%20Entering|Protect%20//%20Serve|Wear%20//%20Tear" height="300px">

**Comment by silasary** [comment]
Also appears to affect other Fuse Cards.  
https://imgur.com/a/5J8JxWr

**Comment by BackAlleyG** [comment]
Fixed in build notes of [ July 10th announcements](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-july-10-2018-2018-07-10).

>Casting a card with fuse now functions correctly
