### ISSUE TITLE
Smallpox does not make players sacrifice things

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#544]
**What is the expected behaviour of the card?**
 - Each player loses 1 life, discards a card, sacrifices a creature, then sacrifices a land.

**What is the actual behaviour of the card?**
 - Each player loses 1 life, and discards a card.  No sacrifices happen.

**Screenshot**
https://clips.twitch.tv/AmericanPiercingFalconDatSheffy

**Please provide a list of affected cards**
Affects: [Smallpox]

**Card Images**

 <img src="http://magic.bluebones.net/proxies/index2.php?c=Smallpox" height="300px">

**Comment by stash86** [comment]
Seems like it fixed. Just got pox'd

**Comment by stash86** [comment]
Just to update this, this fix only been noted in this build note

https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-july-24-2018-2018-07-24
