### ISSUE TITLE
Choosing not to play Consuming Vapors with its Rebound Ability allows you to play it from exile at sorcery speed at any time.

### ISSUE THREAD

**Issue by Odintu** [PennyDreadfulMTG/modo-bugs#546]
**What is the expected behaviour of the card?**
 -  If the player chooses not to play a card that's been exiled due to its own Rebound Ability, it will remain in exile and not be playable.

**What is the actual behaviour of the card?**
 - If the player chooses not to play [Consuming Vapors] through its Rebound ability, it will stay in exile but the player can play it any time they could play a sorcery. This persists through multiple turns and phases as well.

**Screenshot**
https://www.youtube.com/watch?v=KyMjNmluo08

**Please provide a list of affected cards**
Affects: [Consuming Vapors], and possibly any other spell with Rebound as well.

**Card Images**
 <img src="http://magic.bluebones.net/proxies/index2.php?c=Consuming%20Vapors" height="300px">

**Comment by Rowsol** [comment]
I'm seriously contemplating selling my account.
