### ISSUE TITLE
Courser of Kruphix incorrectly shows the top card with shocklands before the land's controller decides to pay two life or not

### ISSUE THREAD

**Issue by Spencerbot15** [PennyDreadfulMTG/modo-bugs#547]
**What is the expected behaviour of the card?**
After you play a shockland from the top of your library, the top card will not be revealed until the player chooses whether or not to pay two life

because playing lands doesn't use the stack, there's theoretically not a moment where the card is no longer the top card of your library but hasn't yet entered the battlefield.

So to choose -as- you play the land, you have to choose before you reveal the new top card of your  library.

**What is the actual behaviour of the card?**
The new top card is incorrectly revealed before the land's controller decides to pay two life or not

**Screenshot**
https://youtu.be/ZXhED2P1xMk?t=16m41s

**Please provide a list of affected cards**
Affects: [Courser of Kruphix]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Courser%20of%20Kruphix/" height="300px">

**Comment by Spencerbot15** [comment]
Testing needed for all cards that allow you to play from the top with replacement effects. Eg. Garruk's Packleader with Clone

**Comment by stash86** [comment]
Garruk's Horde isn't affected with this bug because creature spell need to use the stack. So if you cast Clone from the top of the library, when Clone is in the stack, you MUST reveal the new top card of your library

**Comment by Spencerbot15** [comment]
Ok, that's true. I forgot about that. What if a creature was cast with additional costs, or future sight/oracle of mul daya with shocklands

**Comment by stash86** [comment]
The root of the problem (in my opinion) is how MTGO handles shockland. The way they handle it, it behaves as if the "choice to pay of 2 life or not" works af if it's an ETB trigger. 

When the prompt window ask you whether you want to pay 2 life or not, the shockland has really left the library, and you have a new card on top of your library. Since courser's ability is a static, so it have to show the new top card.

In paper, you must have already make the choice as you put the lands into play. So there is no such delay that we get in mtgo

**Comment by stash86** [comment]
The way MTGO handles "As ... enters the battlefield" is the reason I (and some players) thought they can prevent Living Lore to exile Cruel Ultimatum after LL resolved (and the reason for this bug)

LL would enter the battlefield first, and then the prompt window would appear. So I once thought I can either
a. Exile Ultimatum after my opp choose it using instant-speed GY removal, or
b. Kill LL before the choice resolve

**Comment by stash86** [comment]
Fixed
