### ISSUE TITLE
The land from Spoils of Victory comes into play tapped

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#57]
Affects: [Spoils of Victory]
 <img src="https://pennydreadfulmagic.com/image/Spoils%20of%20Victory/" height="300px">

**Comment by jmeka** [comment]
https://www.youtube.com/watch?v=FR2T6yabdKA

**Comment by BackAlleyG** [comment]
Still bugged.

Affects: [Spoils of Victory]

**Comment by stash86** [comment]
Fixed
