### ISSUE TITLE
Bonds of Mortality gives everything hexproof?

### ISSUE THREAD

**Issue by zinnerzPT** [PennyDreadfulMTG/modo-bugs#587]
**What is the expected behaviour of the card?**
 - All creatures lose hexproof and indestructible until end of turn.

**What is the actual behaviour of the card?**
 - Creatures stopped having the "hexproof" text on them, but were still untargettable. (forcing the Skinrender controller to target one of his own creatures with the ETB trigger)

**Screenshot**
![image](https://user-images.githubusercontent.com/2437964/43933973-9a9d8928-9c44-11e8-9e4c-6c8d19dd24ee.png)

**Please provide a list of affected cards**
Affects: [Bonds of Mortality]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Bonds%20of%20Mortality/" height="300px">

**Comment by datrobino** [comment]
fixed as of 10/16/2021. only bug i can find is a visual bug that gives the creature "doesn't have hexproof. doesn't have hexproof" instead of "doesn't have hexproof. doesnt have indestructable

**Comment by silasary** [comment]
Thanks
