### ISSUE TITLE
Death Cloud causes Soft Lock after Life Loss step occurs

### ISSUE THREAD

**Issue by h1vem1nd85** [PennyDreadfulMTG/modo-bugs#588]
**What is the expected behaviour of the card?**
Each player loses X life, discards X cards, sacrifices X creatures, sacrifices X lands

**What is the actual behaviour of the card?**
Each player loses X life, Death Cloud remains on the stack and the "Main phase" and "Ok" panel appears. No actions can be taken by either player. Death Cloud does not continue to resolve through its remaining X steps.

**Screenshot**
Gamestate prior to Death Cloud resolving
![ss1](https://user-images.githubusercontent.com/36481048/44033219-b59c7fe6-9ed7-11e8-9c21-770910e78bb0.png)

Gamestate after Death Cloud resolves. Both players lost 2 life (X=2) but no further actions can be taken by either player.
![ss2](https://user-images.githubusercontent.com/36481048/44033237-c81f1610-9ed7-11e8-97e2-46c4799fb2ac.png)

**Please provide a list of affected cards**
Affects: [Death Cloud]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Death%20Cloud/" height="300px">

**Comment by silasary** [comment]
Still bugged https://www.reddit.com/r/MTGO/comments/9csbaq/death_clouds_is_still_bugged_since_june/

**Comment by BackAlleyG** [comment]
This has ben fixed.
