### ISSUE TITLE
Hellion Eruption doesn't create tokens and sacrifices all your permanents

### ISSUE THREAD

**Issue by Pixywing** [PennyDreadfulMTG/modo-bugs#589]
Hellion Eruption should sacrifice all of your creatures and give you 4/4 hellions. Currently the card makes you instead sacrifice EVERY permanent you have Planeswalkers, Artifacts, Enchantments, Creatures, and even all your Lands while giving you NOTHING.

https://youtu.be/WXX3LTqYmXQ

Affects: [Hellion Eruption]
 <img src="https://pennydreadfulmagic.com/image/Hellion%20Eruption/" height="300px">

**Comment by urdothor** [comment]
![untitled](https://user-images.githubusercontent.com/47337055/52238510-c4e19d80-2891-11e9-8f8e-a80956d85120.png)
![untitled2](https://user-images.githubusercontent.com/47337055/52238517-ca3ee800-2891-11e9-8b11-abb4989aa6e6.png)
Based on testing, Hellion eruption appears to be working now

**Comment by bakert** [comment]
Fixed as above.
