### ISSUE TITLE
[Djinn of Infinite Deceits] can only be activated at sorcery speed

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#59]

**Comment by Pseudodude** [comment]
It looks like this has been fixed. I don't own the card so I can't double-check, but it definitely worked for my opponent on my EOT.

![djinn_of_infinite_deceits_used_eot](https://user-images.githubusercontent.com/22277621/34907782-f0caa6e8-f8d7-11e7-9f09-60edb1cf88f8.jpg)

**Comment by stash86** [comment]
Great. Closing this issue
