### ISSUE TITLE
Cards that target a land and ask you to choose a basic land type to change it to default to Swamp, regardless of choice.

### ISSUE THREAD

**Issue by jmeka** [PennyDreadfulMTG/modo-bugs#595]
**What is the expected behaviour of the card?**
 - Lands targetted by spell will change to user's desired basic land type.

**What is the actual behaviour of the card?**
 - Lands targetted by spell will change to Swamp, regardless of choice.

**Screenshot**
![land1](https://user-images.githubusercontent.com/28836887/44833116-11e28900-abfb-11e8-91fc-7bd9fd08ea81.JPG)
![land2](https://user-images.githubusercontent.com/28836887/44833117-127b1f80-abfb-11e8-9e1f-3aa4322b9574.JPG)
![land3](https://user-images.githubusercontent.com/28836887/44833118-127b1f80-abfb-11e8-9635-fb3609ddd0bb.JPG)
![land4](https://user-images.githubusercontent.com/28836887/44833119-127b1f80-abfb-11e8-98a1-8421a9724ec2.JPG)

**Please provide a list of affected cards**
Affects: [Convincing Mirage],[Phantasmal Terrain]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Convincing%20Mirage|Phantasmal%20Terrain/" height="300px">

**Comment by stash86** [comment]
Fixed according to [Nov 13th Build Notes](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-november-13-2018-2018-11-13#Build%20Notes)
