### ISSUE TITLE
[Grinning Ignus] The ability supposed to be sorcery speed, but it can be activated anytime

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#6]

**Comment by jmeka** [comment]
Here's a short video of the bug in progress: https://www.youtube.com/watch?v=HLWNNM5pt1o

**Comment by silasary** [comment]
Fixed in [July 11 build notes](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-july-11-2017#item8)
