### ISSUE TITLE
[Null Chamber] owner chooses instead of opponent

### ISSUE THREAD

**Issue by Shantu58** [PennyDreadfulMTG/modo-bugs#60]
![image](https://user-images.githubusercontent.com/7136450/27245981-d60a4046-52ee-11e7-82a0-9708e522475a.png)  
The selection sounded somewhat bugged too (not in alphabetical order?), but no details about that.

**Comment by silasary** [comment]
The selection is wrong:  #16

**Comment by silasary** [comment]
Updated existing issue with secondary bug.
