### ISSUE TITLE
Orator of Ojutai's triggered ability will draw a card only when you control a dragon

### ISSUE THREAD

**Issue by JarJarThinks** [PennyDreadfulMTG/modo-bugs#614]
What is the expected behaviour of the card?**
Orator of Ojutai draw a card when you reveal a dragon or when you have a dragon under your control

**What is the actual behaviour of the card?**
Orator of Ojutai doesn't draw a card when you reveal a dragon, only when you have a dragon under your control

**Screenshot**
https://youtu.be/KRlo3U_4jZQ

**Please provide a list of affected cards**
Affects: [Orator of Ojutai]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Orator%20of%20Ojutai/" height="300px">

**Comment by bakert** [comment]
JayceArveduin reports fixed
