### ISSUE TITLE
Price of Fame does not reduce in cost when it targets a legendary creature

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#651]
Acknowledged by Orcs 
Affects: [Price of Fame]
 <img src="https://pennydreadfulmagic.com/image/Price%20of%20Fame/" height="300px">

**Comment by BackAlleyG** [comment]
Fixed in build notes of [December 18th announcements](https://magic.wizards.com/en/articles/archive/feature/magic-online-announcements-december-2018-12-18).

>Savage Stomp and Price of Fame correctly have their costs reduced when their conditions are met.
