### ISSUE TITLE
Harness the Storm Doesn't trigger when casting split cards.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#7]
Affects: [Harness the Storm]
Bug Blog Text: Split cards do not trigger [Harness the Storm].

 <img src="https://pennydreadfulmagic.com/image/Harness%20the%20Storm/" height="300px">

**Comment by jmeka** [comment]
Still bugged. It was hard to make a screenshot of something not being triggered, so here's a video:
https://youtu.be/wwSfMn_dZEg

**Comment by Greedy00010** [comment]
it also doesn't work for aftermath cards 
https://i.gyazo.com/c9929ea7ab768a09da8a551d89d76e9e.jpg

**Comment by stash86** [comment]
Still bugged

**Comment by stash86** [comment]
Surprisingly this is fixed
