### ISSUE TITLE
Kess, Dissident Mage has issues with casting spells through alternative methods.

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#705]
From Bug Blog.
Bug Blog Text: [Kess, Dissident Mage] has issues with casting spells through alternative methods.
Affects: [Kess, Dissident Mage]
 <img src="https://pennydreadfulmagic.com/image/Kess%2C%20Dissident%20Mage/" height="300px">

**Comment by datrobino** [comment]
vague, and seems fixed
