### ISSUE TITLE
Volcanic Offering doesn't allow opponent selection when copied

### ISSUE THREAD

**Issue by breadbocks** [PennyDreadfulMTG/modo-bugs#706]
**What is the expected behaviour of the card?**
 Copies of Volcanic Offering allow choosing an opponent who then has the choice of changing the targets the opponent made for the original Volcanic Offering

**What is the actual behaviour of the card?**
 The owner of VO can freely redirect any of the targets, including ones originally chosen by an opponent 

**Screenshot**
https://youtu.be/vTZPA1WSbGs?t=3679

**Please provide a list of affected cards**
Affects: [Volcanic Offering]

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by silasary** [comment]
This is actually the correct behaviour.
