### ISSUE TITLE
Swirl the Mists crashes the game

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#708]
Mentioned in the introduction of https://youtu.be/u0HUlmH7hhQ

**Please provide a list of affected cards**
Affects: [Swirl the Mists]
 <img src="https://pennydreadfulmagic.com/image/Swirl%20the%20Mists/" height="300px">

**Comment by datrobino** [comment]
merging with https://github.com/PennyDreadfulMTG/modo-bugs/issues/848

**Comment by datrobino** [comment]
i cant actually find a trigger for this. could be fixed, could just be that i couldnt figure out cause. im going to tentatively close this.
