### ISSUE TITLE
Restarting the game with Karn Liberated restarts the game (But not in the good way)

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#710]
**What is the expected behaviour of the card?**
 - The game restarts, and you begin the game with the exiled permanents.

**What is the actual behaviour of the card?**
 - The game restarts, loops two times, then restarts in a buggy state.  Without the permanents.

**Screenshot**
https://youtu.be/QGa7AoCTXwg?t=2594

**Please provide a list of affected cards**
Affects: [Karn Liberated]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Karn%20Liberated/" height="300px">

**Comment by Kalioc** [comment]
Fixed.
https://youtu.be/yrUf29Cdfss?t=3675
