### ISSUE TITLE
Attacking with Explorer's Scope restarts the game (but not in the good way)

### ISSUE THREAD

**Issue by willdana** [PennyDreadfulMTG/modo-bugs#713]
**What is the expected behaviour of the card?**
 - When attacking with a creature equipped with Explorer's Scope, the top card of your library is revealed. If it is a land, it's put into play.

**What is the actual behaviour of the card?**
 - When attacking with a creature equipped with Explorer's Scope, the game restarts, loops two times, then restarts in a buggy state. In solitaire mode, the game just restarts without looping (and this appears to not happen consistently).

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Explorer's Scope]
Bug Blog Text: [Explorer's Scope] can cause the game to be reset.

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Explorer%27s%20Scope/" height="300px">

**Comment by Kalioc** [comment]
Seemingly fixed. No restarts in solitaire or multiplayer.
![image](https://user-images.githubusercontent.com/9436442/93693206-c42f6680-faca-11ea-9d9c-cde2191e216f.png)
![image](https://user-images.githubusercontent.com/9436442/93693278-c645f500-facb-11ea-88ca-c2169bf08d6b.png)

**Comment by silasary** [comment]
Thanks :)
