### ISSUE TITLE
If a player would draw from an empty library with Zur's Weirding in play, that player can't be made to lose, and the replacement effect stops functioning.

### ISSUE THREAD

**Issue by tsutton** [PennyDreadfulMTG/modo-bugs#714]
**What is the expected behaviour of the card?**
 - In the situation: Either player controls Zur's Weirding. Player X has 0 cards in library and is about to draw. The expected behavior is that another player Y should be offered to pay 2 life or let player X draw, and if life is not paid, player X should lose from drawing from an empty library.

**What is the actual behaviour of the card?**
 -  In the situation above, other players are not offered the dialog to pay life, player X does not lose, and for the rest of the game, no player is offered the chance to pay life to prevent drawing cards and the drawn cards are not revealed (however, hands are still revealed).

**Screenshot**
No screenshot yet, however it was tested by myself and 4433 on 5/24/2019.

**Please provide a list of affected cards**
Affects: [Zur's Weirding]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Zur%27s%20Weirding/" height="300px">

**Comment by tsutton** [comment]
Zur's Weirding is symmetric, so I'm not sure how to classify it as advantageous vs disadvantageous - if I'm puting weirding in my deck, do I expect to be winning by milling my opponent?

**Comment by bakert** [comment]
Fixed according to LudwigFrito
