### ISSUE TITLE
Crovax The Cursed loses old counters after sacrifice 

### ISSUE THREAD

**Issue by breadbocks** [PennyDreadfulMTG/modo-bugs#757]
**What is the expected behaviour of the card?**
 - Sacrificing a creature on upkeep due to the trigger will increment the number of +1/+1 counters on it by 1.

**What is the actual behaviour of the card?**
 - The number of counters reset to 1.

**Screenshot**
https://clips.twitch.tv/AstuteBlueSpaghettiBIRB

**Please provide a list of affected cards**
Affects: [Crovax The Cursed]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Crovax%20The%20Cursed/" height="300px">

**Comment by datrobino** [comment]
merge this with https://github.com/PennyDreadfulMTG/modo-bugs/issues/989 and see if there are any others that do this
