### ISSUE TITLE
Yixlid Jailer allows some cards to be cast from the graveyard

### ISSUE THREAD

**Issue by Ramy99** [PennyDreadfulMTG/modo-bugs#758]
**What is the expected behaviour of the card?**
 - Cards in graveyards lose all abilities

**What is the actual behaviour of the card?**
 - Gravecrawler and Hogaak do not appear to lose the ability "this card can be cast from the graveyard" while jailer is on the battlefield, it may affect other cards with that ability as well

**Screenshot**

**Please provide a list of affected cards**

Affects: [Yixlid Jailer]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Yixlid%20Jailer/" height="300px">

**Comment by silasary** [comment]
Fixed in [Build Notes](https://magic.wizards.com/en/articles/archive/magic-online/magic-online-announcements-july-9-2019)
