### ISSUE TITLE
Tidal Warrior's activated ability removes all abilities from the targetted land

### ISSUE THREAD

**Issue by jmeka** [PennyDreadfulMTG/modo-bugs#759]
**What is the expected behaviour of the card?**
 - [Tidal Warrior] turns targetted land into an Island.

**What is the actual behaviour of the card?**
 - When ability is activated, the land targeted becomes unusable (for mana at least) until end of turn

**Screenshot**
![image](https://user-images.githubusercontent.com/1541/85329109-c0b62000-b486-11ea-8caa-6db639515327.png)

**Please provide a list of affected cards**
Affects: [Tidal Warrior], [Streambed Aquitects]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Tidal%20Warrior|Streambed%20Aquitects/" height="300px">

**Comment by bakert** [comment]
https://twitter.com/LordMajicus/status/1266166011813859328

Looks like this is no longer game-breaking but now makes the land unusable rather than an Island.

**Comment by Kalioc** [comment]
Has been fixed.
https://twitter.com/LordMajicus/status/1375243288500969476?s=19
