### ISSUE TITLE
Consul's Lieutenant doesn't grant +1/+1 to other attacking creatures.

### ISSUE THREAD

**Issue by tsutton** [PennyDreadfulMTG/modo-bugs#761]
**What is the expected behaviour of the card?**
 - If it is renowned and attacks, it should grant other attacking creatures +1/+1.

**What is the actual behaviour of the card?**
 - The ability does trigger, but it instead grants "Attacks each combat if able."

**Screenshot**
![consuls](https://user-images.githubusercontent.com/99064/60902436-765f7300-a224-11e9-966a-d4ce9f43dc6b.PNG)

**Please provide a list of affected cards**
Affects: [Consul's Lieutenant]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Consul%27s%20Lieutenant/" height="300px">

Affects:

**Comment by silasary** [comment]
Reported fixed by Archangal
