### ISSUE TITLE
City of Traitors triggers by casting Zoetic Cavern as a Morph creature

### ISSUE THREAD

**Issue by f7eleven** [PennyDreadfulMTG/modo-bugs#769]
**What is the expected behaviour of the card?**
 - That it only triggers when playing a Land card from your hand

**What is the actual behaviour of the card?**
 - It triggers when you cast Zoetic Cavern as a Morph creature

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Zoetic Cavern]
See Also: [City of Traitors]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Zoetic%20Cavern/" height="300px"><img src="https://pennydreadfulmagic.com/image/City%20of%20Traitors/" height="250px">

**Comment by datrobino** [comment]
fixed
