### ISSUE TITLE
Daretti, Ingenious Iconoclast creates tokens with the wrong card image

### ISSUE THREAD

**Issue by Ramy99** [PennyDreadfulMTG/modo-bugs#791]
**What is the expected behaviour of the card?**
 - Create a 1/1 construct creature token with defender

**What is the actual behaviour of the card?**
 - Creates a 1/1 construct artifact creature token with defender that has the extra line of text "this creature gets +1/+1 for each artifact you control," although that text does not actually impact the functionality.

**Screenshot**
<img width="989" alt="Daretti" src="https://user-images.githubusercontent.com/25128665/63471592-2f74b800-c435-11e9-9745-d4635358c62a.png">

**Please provide a list of affected cards**
Affects: [Daretti, Ingenious Iconoclast]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Daretti%2C%20Ingenious%20Iconoclast/" height="300px">

**Comment by datrobino** [comment]
fixed
