### ISSUE TITLE
If you activate Mana Bloom after you determine the total cost of the spell or ability, you can't cancel the process of casting the spell or ability

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#823]
**What is the expected behaviour of the card?**
 - If you have determine the total cost of a spell or ability, and now in the process of activating Mana Bloom's ability (CR 601.2g), you can choose to cancel the whole process of casting the spell or activating the ability (CR721.1)

**What is the actual behaviour of the card?**
 - When you try to cancel the spell or ability, the client will bring you to the mana picker window, and basically lock you out of the game

**Screenshot**
https://youtu.be/nK62QPBdy0c

**Please provide a list of affected cards**
Affects: [Mana Bloom]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Mana%20Bloom/" height="300px">

**Comment by datrobino** [comment]
fixed
