### ISSUE TITLE
Bond of Agony bug

### ISSUE THREAD

**Issue by danomyticus** [PennyDreadfulMTG/modo-bugs#827]
**What is the expected behaviour of the card?**
 - should cast one black and x life to take x life from opponent

**What is the actual behaviour of the card?**
 - there seems to be no way to continue after casting the one black to use life to pay x.

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Card Name](, [Second Card name], etc)Bond of Agony

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Card%20Name|Second%20Card%20name/" height="300px">

**Comment by bakert** [comment]
Bond of Agony costs XB not B. You need to pay X mana *as well as* X life.
