### ISSUE TITLE
Thopter Spy Network can trigger too many times in multiplayer

### ISSUE THREAD

**Issue by silasary** [PennyDreadfulMTG/modo-bugs#831]
**What is the expected behaviour of the card?**
 - Each combat damage step, you should be able to draw at most one card, even if you deal damage to multiple players.

**What is the actual behaviour of the card?**
 - You draw one card per opponent per combat damage step.

**Screenshot**
Reported via discord

**Please provide a list of affected cards**
Affects: [Thopter Spy Network]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Thopter%20Spy%20Network/" height="300px">

**Comment by Ramy99** [comment]
This is not a bug, the card is functioning as intended according to https://blogs.magicjudges.org/rulestips/2015/09/thopter-spy-network-draws-only-one-card-for-multiple-artifact-creatures-dealing-damage-at-once/

**Comment by MultiDragon** [comment]
From Scryfall rulings:

> The last ability will trigger, at most, once per combat damage step. 

I guess that means that the card *is* banned.

**Comment by bakert** [comment]
"For example, in Two-Headed Giant (which you may have played at your last prerelease), although both heads share a life total, they’re still two separate players. This means that if you attack with two Thopters, you can assign one Thopter’s damage to Head A, assign the other’s damage to Head B, and draw two cards." is pretty unequivocal. It's just a judge blog but I'd be surprised if they were wrong. Perhaps the rulings are meant for a two player game? I guess a blog is more likely to be wrong than a ruling. Hm.
