### ISSUE TITLE
Thryx, the Sudden Storm doesn't make spells with X in cost uncounterable

### ISSUE THREAD

**Issue by MultiDragon** [PennyDreadfulMTG/modo-bugs#832]
**What is the expected behaviour of the card?**
 - Spells with large enough X cast when Thryx is in play should not be counterable.

**What is the actual behaviour of the card?**
 - Spells with X in cost (large enough so that CMC>=5) with Thryx in play cost 1 cheaper but are counterable.

**Screenshot**
![thryx bug](https://user-images.githubusercontent.com/52964431/74761065-6f094900-528c-11ea-91d8-bebe9144412b.png)
https://logs.pennydreadfulmagic.com/match/226355911/

https://youtu.be/7fA7oUOgUm8

**Please provide a list of affected cards**
Affects: [Thryx, the Sudden Storm]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Thryx%2C%20the%20Sudden%20Storm/" height="300px">

**Comment by stash86** [comment]
@silasary why did the bot gives this Invalid Name tag? Saw nothing wrong

**Comment by bpburns8** [comment]
I believe this is no longer an issue. Have been playing with Thryx and noticed X-cost spells with CMC 5+ are correctly uncounterable. 
Logs: https://logs.pennydreadfulmagic.com/match/229104130/ (Game 2)
![Thryx can't be countered x spells](https://user-images.githubusercontent.com/8559928/80600440-65256400-89fa-11ea-892c-dead0d34ad24.PNG)
