### ISSUE TITLE
Whenever an ability is granted to a creature and then get removed, graphically MTGO will still shows the abilities on the creature

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#833]
**What is the expected behaviour of the card?**
 - When an ability is granted to a creature and then get removed by another ability or effect, that ability should be grayed out graphically

**What is the actual behaviour of the card?**
 - The ability (that correctly get removed from the creature) is still shown in blue text, which implies that the ability is still on the creature

**Screenshot**
https://youtu.be/eRiwHNCgLv8

**Please provide a list of affected cards**
Affects: [Gift of Tusks], etc

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Gift%20of%20Tusks/" height="300px">

**Comment by stash86** [comment]
Wondering if I should tag all 26 cards

https://scryfall.com/search?q=o%3A%22loses+all+abilities%22&unique=cards&as=grid&order=cmc

**Comment by datrobino** [comment]
fixed
