### ISSUE TITLE
Pyroclasm and Oathsworn Knight

### ISSUE THREAD

**Issue by enilson4** [PennyDreadfulMTG/modo-bugs#834]
**What is the expected behaviour of the card?**
 - Pyroclasm does 2 damage to all creatures.

**What is the actual behaviour of the card?**
 - In addition to preventing the damage to Oathsworn Knight - damage is prevented to all opponents creatures and not yours.

**Screenshot**

I have video of it but it's too big to upload.  If you'd like me to upload it somewhere please let me know.

**Please provide a list of affected cards**
Affects: [Oathsworn Knight], [Pyroclasm]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Oathsworn%20Knight|Pyroclasm/" height="300px">

**Comment by stash86** [comment]
can you upload it to youtube?

**Comment by enilson4** [comment]
Sure - good idea . . . I've uploaded it here:

https://youtu.be/4jjHrKtto68

Forgive the first few seconds - was figuring out a new recording app.

**Comment by Kalioc** [comment]
Th Wanderer prevents noncombat damage. Not sure Oathsworn Knight should have lost a counter there.

**Comment by Ramy99** [comment]
With wanderer in play you get to choose which damage prevention effect to apply first, if you apply the oathsworn Knight's effect first it will lose a counter, if you apply the wanderer's first it will not.
