### ISSUE TITLE
Mogis's Marauder restarts the game on etb

### ISSUE THREAD

**Issue by MultiDragon** [PennyDreadfulMTG/modo-bugs#835]
**What is the expected behaviour of the card?**
 - It should work.

**What is the actual behaviour of the card?**
 - It restarts the game.

**Screenshot**
![game log with Mogis's Marauder](https://user-images.githubusercontent.com/52964431/79687068-4cc08700-824d-11ea-9a27-fc555fceafd4.png)

**Please provide a list of affected cards**
Affects: [Mogis's Marauder]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Mogis%27s%20Marauder/" height="300px">

**Comment by stash86** [comment]
Fixed
