### ISSUE TITLE
Scrap Trawler does not trigger

### ISSUE THREAD

**Issue by liltizzel** [PennyDreadfulMTG/modo-bugs#839]
**What is the expected behaviour of the card?**

 - Whenever Scrap Trawler or another artifact you control is put into a graveyard from the battlefield, return to your hand target artifact card in your graveyard with lesser converted mana cost.

**What is the actual behaviour of the card?**

 - Nothing happens when it or another artifact I control dies. They just die. 

**Screenshot**
See below

**Please provide a list of affected cards**
Affects: [Scrap Trawler]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Scrap%20Trawler/" height="300px">

**Comment by MultiDragon** [comment]
![image](https://user-images.githubusercontent.com/52964431/80818032-2a2e5680-8bdb-11ea-803f-2e96847fc02a.png)

**Comment by stash86** [comment]
just tested the card and it's working as intended
