### ISSUE TITLE
As Foretold does not allow you to cast X spells for X=0.

### ISSUE THREAD

**Issue by sh4meus** [PennyDreadfulMTG/modo-bugs#846]
**What is the expected behaviour of the card?**
 - As foretold is supposed to be able to cast any card from your hand equal to it's converted mana cost.

**What is the actual behaviour of the card?**
 - When trying to cast Electrodominance for two cmc (x=0), As Foretold does not show up as an alternate way to cast.

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
[As Foretold] [Electrodominance]

**Card Images**
 

Affects:

**Comment by komo50** [comment]
I am also well experiencing this issue. It seems the problem also exists with Finale of Promise. I have reported them both to wizards. Just might have caused me to lose a match...

**Comment by komo50** [comment]
This has been fixed for both Electrodominance and Finale of promise
