### ISSUE TITLE
Swirl the Mists will randomly restart the game

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#848]
Still can't pinpoint the exact trigger for the restart.

**What is the expected behaviour of the card?**

**What is the actual behaviour of the card?**

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Swirl the Mists]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Swirl%20the%20Mists/" height="300px">

**Comment by silasary** [comment]
Duplicate of #708
