### ISSUE TITLE
Doubling Cube effect does not work

### ISSUE THREAD

**Issue by bananonymouspd** [PennyDreadfulMTG/modo-bugs#854]
**What is the expected behaviour of the card?**
 - Doubling the amount of unspent mana in the mana pool

**What is the actual behaviour of the card?**
 - tapping and paying for the mana of the activated ability does not do anything, does not even show up in the game log

**Screenshot**
Currently Unconfirmed.
![Doubling Cube bug](https://user-images.githubusercontent.com/68799416/88470861-2e2ff300-cf02-11ea-8113-39038ebb30b7.PNG)

**Please provide a list of affected cards**
Affects: [Doubling Cube]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Doubling%20Cube/" height="300px">

**Comment by Kalioc** [comment]
This has been fixed. 
![image](https://user-images.githubusercontent.com/9436442/111355362-adbf2d80-865d-11eb-9eeb-14d9d7191839.png)

**Comment by silasary** [comment]
Thanks :)
