### ISSUE TITLE
Wormfang Newt/Turtle returns MDFCs on their land side, rather than their front side.

### ISSUE THREAD

**Issue by blackvenym** [PennyDreadfulMTG/modo-bugs#867]
**What is the expected behaviour of the card?**
 - Wormfang Newt exiles Umara Skyfalls upon entering the battlefield. When Wormfang Newt leaves the battlefield Umara Wizard/Skyfalls is returned to the battlefield on the "Front" side of Umara Wizard. The expected behavior is that the double-faced card enters with its front face up. If that front face can't be put onto the battlefield, it doesn't enter the battlefield.

**What is the actual behaviour of the card?**
 - When Wormfang Newt leaves the battlefield, The modal flip land is returned on the "land side", in this case Umara Skyfalls.

I have not tested, but I assume this is the case for all of the new modal flip lands. 

**Screenshot**
![image](https://user-images.githubusercontent.com/6083278/95657116-bf197200-0ae0-11eb-9d00-816eb72a49eb.png)
![MTGO_dK8gJz2UxQ](https://user-images.githubusercontent.com/6083278/95657256-7f06bf00-0ae1-11eb-9bfe-da45e1676074.png)
![MTGO_3G4QV60bxP](https://user-images.githubusercontent.com/6083278/95657264-8af28100-0ae1-11eb-8197-9f2c847b10c6.png)

**Please provide a list of affected cards**
Affects: [Wormfang Newt], [Wormfang Turtle]

**Card Images**

 <img src="https://pennydreadfulmagic.com/image/Wormfang%20Newt|Wormfang%20Turtle/" height="300px">

**Comment by datrobino** [comment]
fixed 
![image](https://user-images.githubusercontent.com/85389721/149261621-d61f7fb6-b90a-4aec-ac1d-7f32a980f9ac.png)
