### ISSUE TITLE
Epic Experiment allows you to play the land side of MDFCs.

### ISSUE THREAD

**Issue by Kalioc** [PennyDreadfulMTG/modo-bugs#868]
**What is the expected behaviour of the card?**
 - Epic Experiment allows you to cast any instant or sorcery it exiles and not play the land side of modal double-faced cards.

**What is the actual behaviour of the card?**
 - Epic Experiment will allow you to play the land side of modal double-faced cards.

**Screenshot**
![image](https://user-images.githubusercontent.com/9436442/95766031-b1025780-0c80-11eb-94a9-541fdb6243cf.png)

**Please provide a list of affected cards**
Affects: [Epic Experiment]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Epic%20Experiment/" height="300px">

**Comment by datrobino** [comment]
fixed
