### ISSUE TITLE
Cards with "bands with other" can't be collected.

### ISSUE THREAD

**Issue by Skagra42** [PennyDreadfulMTG/modo-bugs#869]
**What is the expected behaviour of the card?**
 - Being found when looking for collectible cards.

**What is the actual behaviour of the card?**
 - Can only be found when looking for non-collectible cards.

**Screenshot**
![Screenshot (15)](https://user-images.githubusercontent.com/72851315/95950463-cf1ba500-0db1-11eb-9977-d6dd948f3f72.png)

**Please provide a list of affected cards**
Affects: 
Shelkin Brownie
Adventurers' Guildhouse
Master of the Hunt
Mountain Stronghold
Cathedral of Serra
Unholy Citadel
Seafarer's Quay

**Card Images**

**Comment by emerald000** [comment]
Those cards were never released on MTGO.
