### ISSUE TITLE
Phytotitan returns to the battlefield under it's controller's control, rather than its owner's control.

### ISSUE THREAD

**Issue by Ksym77** [PennyDreadfulMTG/modo-bugs#870]
**What is the expected behaviour of the card?**
 - A Phytotitan you own that is controlled by your opponent that is destroyed should return to the battlefield tapped under your control at the beginning of your next upkeep.

**What is the actual behaviour of the card?**
 - It returns untapped under your control at the beginning of the opponent’s next upkeep.

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Phytotitan]
**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Phytotitan/" height="300px">

**Comment by datrobino** [comment]
fixed
