### ISSUE TITLE
Apostle's Blessing affects everything, even cards in hand.

### ISSUE THREAD

**Issue by BenHR555** [PennyDreadfulMTG/modo-bugs#875]
**What is the expected behaviour of the card?**
 - Apostle's Blessing, upon resolution, gives only the creature it targeted protection from the chosen color.

**What is the actual behaviour of the card?**
 - Apostle's Blessing will give protection to all creatures the player controls of the chosen color.
 - Cards in the player's hand will also be given the quality of protection from the chosen color. Whether this results in an effect to gameplay is currently unknown.
- The player who cast Apostle's Blessing will also be given protection from the chosen color.

**Screenshot**
![image](https://user-images.githubusercontent.com/73731284/99707927-c11d0c00-2a62-11eb-90c2-eabc57e026d3.png)
![image](https://user-images.githubusercontent.com/73731284/99709696-32f65500-2a65-11eb-9094-11600d69d593.png)

**Please provide a list of affected cards**
Affects: [Apostle's Blessing]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Apostle%27s%20Blessing/" height="300px">

**Comment by silasary** [comment]
https://twitter.com/MagicOnline/status/1329582091835588609
