### ISSUE TITLE
Curse of the Pierced Heart triggers on each players' upkeep

### ISSUE THREAD

**Issue by stash86** [PennyDreadfulMTG/modo-bugs#876]
**What is the expected behaviour of the card?**
 - CotPH only triggers on enchanted player's upkeep

**What is the actual behaviour of the card?**
 - CotPH triggers on each upkeep and deal damage to the current active player

**Screenshot**
Currently Unconfirmed.
![image](https://user-images.githubusercontent.com/13656154/99797640-fe70bf00-2b72-11eb-8a4d-5330cfd82873.png)

**Please provide a list of affected cards**
Affects: [Curse of the Pierced Heart]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Curse%20of%20the%20Pierced%20Heart/" height="300px">

**Comment by Kalioc** [comment]
![image](https://user-images.githubusercontent.com/9436442/106806679-3f3a8900-6636-11eb-8f36-7c7588beebe6.png)
Fixed, only activating on the cursed player's turn.
