### ISSUE TITLE
Ctrl+Z two Deranged Assistants can soft-lock the game

### ISSUE THREAD

**Issue by NicholasMarino** [PennyDreadfulMTG/modo-bugs#877]
**What is the expected behaviour of the card?**
 - You are not supposed to be able to un-do a Deranged Assistant activation.

**What is the actual behaviour of the card?**
 -  The game has some odd short-cut, which just gives you the mana back. However, if you have two of the abilities, it will only give you one mana back instead of two. 

- If you announce the casting of a spell, and you tap two deranged assistants to pay for it, then Ctrl+Z both of them, and are unable to pay for the spell, the game will soft-lock. 

**Please provide a list of affected cards**
Affects: [Deranged Assistant]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Deranged%20Assistant/" height="300px">
![Soft-Lock](https://user-images.githubusercontent.com/6447969/99861774-e726d700-2b5c-11eb-8ff8-24165eaa5fd9.jpg)

**Comment by datrobino** [comment]
you cannot undo the activation of deranged assistant any more
