### ISSUE TITLE
Embalmed cards' CMC is treated as 0 instead of the original card's cmc

### ISSUE THREAD

**Issue by MultiDragon** [PennyDreadfulMTG/modo-bugs#881]
**What is the expected behaviour of the card?**
 - From Lavabrink Venturer's scryfall page:
 - ```The converted mana cost of a token that isn’t a copy of another object is 0. A token that is a copy of another object has the same converted mana cost as that object. ```

**What is the actual behaviour of the card?**
 - Champion of Wits's embalmed token has CMC of 0 therefore Lavabrink Venturer on even is protected from it,

**Screenshot**
![image](https://user-images.githubusercontent.com/52964431/103403261-91344e80-4b60-11eb-8f07-bd0c75ce5bb1.png)

**Please provide a list of affected cards**
Affects: [Champion of Wits]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Champion%20of%20Wits/" height="300px">

**Comment by jgabrielygalan** [comment]
From the Eternalize rule expansion on the card: 
Eternalize {5}{U}{U} ({5}{U}{U}, Exile this card from your graveyard: Create a token that’s a copy of it, except it’s a 4/4 black Zombie Naga Wizard with no mana cost. Eternalize only as a sorcery.)

Note the **with no mana cost**

**Comment by MultiDragon** [comment]
Wow I'm so dumb.
