### ISSUE TITLE
Animate Dead's LTB trigger restarts the game

### ISSUE THREAD

**Issue by MultiDragon** [PennyDreadfulMTG/modo-bugs#884]
**What is the expected behaviour of the card?**
 - When Animate Dead leaves the battlefield, the creature it was enchanted to is sacrificed.

**What is the actual behaviour of the card?**
 - Animate Dead's ability does not trigger, and the game is restarted.

**Screenshot**
https://user-images.githubusercontent.com/52964431/106136980-1ec48780-617b-11eb-8512-7637e5817a36.mov

**Please provide a list of affected cards**
Affects: [Animate Dead]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Animate%20Dead/" height="300px">

**Comment by jgabrielygalan** [comment]
https://user-images.githubusercontent.com/247560/106141078-ec615d00-616f-11eb-967e-63110556abd5.mp4

Thanks to Alex (wizzerinus) for the video.

**Comment by bakert** [comment]
<img width="1790" alt="Screen Shot 2021-01-28 at 6 26 32 PM" src="https://user-images.githubusercontent.com/1541/106223545-76bcb780-6196-11eb-8d28-1b1bdd90bb4a.png">

**Comment by bakert** [comment]
Restarts the game and takes you directly to the cleanup step each turn in the restarted game. Oops.

**Comment by jmeka** [comment]
fixed
