### ISSUE TITLE
Svella, Ice Shaper's second ability shows incorrect text (but works correctly)

### ISSUE THREAD

**Issue by Wizzerinus** [PennyDreadfulMTG/modo-bugs#896]
**What is the expected behaviour of the card?**
 - When you activate second ability, look at the top four cards of your library. You may cast a spell from among them without paying its mana cost. Put the rest on the bottom of your library in a random order.

**What is the actual behaviour of the card?**
 - MTGO says "cast any number of cards from this pile". You still can only cast one

**Screenshot**
![image](https://user-images.githubusercontent.com/52964431/108552294-2a324b00-7302-11eb-9a2f-b552473e987c.png)

**Please provide a list of affected cards**
Affects: [Svella, Ice Shaper]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Svella%2C%20Ice%20Shaper/" height="300px">

**Comment by MultiDragon** [comment]
oops i didnt mean to submit like this

**Comment by bakert** [comment]
You can click on the three dots and click Edit

**Comment by MultiDragon** [comment]
fixed!

**Comment by datrobino** [comment]
fixed
