### ISSUE TITLE
Gaea's Blessing doesn't shuffle opponent's library if no cards in their graveyard are targeted

### ISSUE THREAD

**Issue by Vequinox** [PennyDreadfulMTG/modo-bugs#902]
**What is the expected behaviour of the card?**
 - As per one of the ruling on Gaea's blessing: _If Gaea’s Blessing has no legal target cards in a graveyard, either because its targets became illegal or **because you didn’t choose any**, the target player shuffles their library._ Thus, I expect not choosing cards in the opponent's graveyard to still shuffle their library.

**What is the actual behaviour of the card?**
 - Targeting no cards in the opponent's graveyard does not shuffle their deck as expected by the rule cited above.

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Gaea's Blessing]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Gaea%27s%20Blessing/" height="300px">

**Comment by Kalioc** [comment]
Video of the bug.
https://streamable.com/99olm4

**Comment by datrobino** [comment]
fixed
