### ISSUE TITLE
Glimpse the Cosmos exiles from hand instead of from graveyard

### ISSUE THREAD

**Issue by walloficecream** [PennyDreadfulMTG/modo-bugs#905]
**What is the expected behaviour of the card?**
 - When played from hand, the card draws a card and goes into the graveyard.  When played from the graveyard, it gets exiled.

https://user-images.githubusercontent.com/80441373/110736242-4b97a000-81f9-11eb-9bf4-fd8bb2cd8dad.mp4

**What is the actual behaviour of the card?**
 - When played from hand, the card draws a card and gets removed from the game (exiled.)  In other words, the card never hits the graveyard. It's never able to be played from the graveyard, or in other words, cast a second time. There are no R.I.P. effects in the video (attached,) therefore I think it's bugged.

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Glimpse the Cosmos]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Glimpse%20the%20Cosmos/" height="300px">

**Comment by Kalioc** [comment]
Dryad Militant exiles instants and sorceries, which Glimpse was exiled.
