### ISSUE TITLE
Weathered Runestone doesn't work

### ISSUE THREAD

**Issue by savomtg** [PennyDreadfulMTG/modo-bugs#907]
**What is the expected behaviour of the card?**
 - stopping permanents from entering the battlefield from libraries

**What is the actual behaviour of the card?**
 - It did not stop creatures from entering the battlefield from the library, both from my side and opponent's side

**Please provide a list of affected cards**
Affects: Polymorph, Proteus Staff

**Card Images**

**Comment by Kalioc** [comment]
Tested Runestone against Planar Bridge and it does stop Planar Bridge from putting in nonland permanents. I'm going to test this with more cards but this might be a bug with Proteus Staff instead.

**Comment by savomtg** [comment]
Runestone also did not stop Polymorph, as well. Unlikely that they (staff and polymorph) are both bugged? 

> Tested Runestone against Planar Bridge and it does stop Planar Bridge from putting in nonland permanents. I'm going to test this with more cards but this might be a bug with Proteus Staff instead.
> https://streamable.com/87b8k3

**Comment by Kalioc** [comment]
I have opened a new issue for Runestone, and included Grafdigger's cage. Both of them aren't working against cards with effects similar to Polymorph or Proteus Staff, but function correctly otherwise.
