### ISSUE TITLE
Bogardan Hellkite doesn't show targets

### ISSUE THREAD

**Issue by MartinAparicioPons** [PennyDreadfulMTG/modo-bugs#914]
**What is the expected behaviour of the card?**
 - To show all the targets for the ETB and the damage assigned.

**What is the actual behaviour of the card?**
 - It once didn't show any targets, after being put into the field with Hypergenesis. During the match, the two following times it was put into the battlefield this way it showed the targets correctly.

**Screenshot**
(Attach a screenshot or video here)

**Please provide a list of affected cards**
Affects: [bogardan hellkite], [hypergenesis]

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by Kalioc** [comment]
If you could go into your game history on MTGO and get a screenshot that would be helpful, but since you say it worked in later and is personally working for me, I'm going to close this issue.
