### ISSUE TITLE
Guardian of the Guildpact is untargettable by the triggered abilities of multicolored permanents.

### ISSUE THREAD

**Issue by Kalioc** [PennyDreadfulMTG/modo-bugs#916]
**What is the expected behaviour of the card?**
 - Guardian of the Guildpact should be targetable by triggers of multicolored permanents since it only has protection from monocolored.

**What is the actual behaviour of the card?**
 - Guardian isn't targetable by any triggered ability of a colored permanent.

**Screenshot**
![guildpact_one](https://user-images.githubusercontent.com/9436442/116834104-9810b380-ab8a-11eb-9cc7-5f10596c32d8.PNG)
![guildpact_two](https://user-images.githubusercontent.com/9436442/116834129-a5c63900-ab8a-11eb-834d-707f527e94f2.PNG)
![guildpact_three](https://user-images.githubusercontent.com/9436442/116834131-a8c12980-ab8a-11eb-8158-9913d79b6378.PNG)
![guildpact_four](https://user-images.githubusercontent.com/9436442/116834136-aa8aed00-ab8a-11eb-9904-3d68656d3626.PNG)
![guildpact_five](https://user-images.githubusercontent.com/9436442/116834137-abbc1a00-ab8a-11eb-82e3-4867abb2c8c1.PNG)

**Please provide a list of affected cards**
Affects: [Guardian of the Guildpact]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Guardian%20of%20the%20Guildpact/" height="300px">

**Comment by datrobino** [comment]
fixed
