### ISSUE TITLE
Conceding the game during the cleanup step after having activated Unearth will restart the game.

### ISSUE THREAD

**Issue by Kalioc** [PennyDreadfulMTG/modo-bugs#925]
**What is the expected behaviour of the card?**
 - Creatures with Unearth shouldn't effect concessions.

**What is the actual behaviour of the card?**
 - Unearthing creatures can be used to restart the game if you concede the game during cleanup step with an eight card hand, after exiling an unearthed creature. Conceding during the discard prompt will _eventually_ restart the game.

**Screenshot**
https://streamable.com/mxjddk

**Please provide a list of affected cards**
Affects: [Fatestitcher], [Hellspark Elemental], [Sedraxis Specter], etc.

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Fatestitcher|Hellspark%20Elemental|Sedraxis%20Specter/" height="300px">

**Comment by Kalioc** [comment]
https://www.reddit.com/r/magicTCG/comments/nvn21h/how_to_start_a_brand_new_game_3_on_mtgo_in_case/
Source for where I found this bug. I was struggling to reproduce it to how they describe it but it seemingly does loop back through the game at minimum.

**Comment by datrobino** [comment]
i tested this and it seems to be fixed
