### ISSUE TITLE
Kaya's Ghostform

### ISSUE THREAD

**Issue by rblakedavis** [PennyDreadfulMTG/modo-bugs#927]
**What is the expected behaviour of the card?**
 
 - Returns the enchanted to the creature when it dies or is exiled.

**What is the actual behaviour of the card?**
 - Nothing happens 

**Screenshot**
https://youtu.be/yXI29ZE_rkQ
https://youtu.be/EIDD_4KVDSU

**Please provide a list of affected cards**
Affects: [Kaya's Ghostform]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Kaya%27s%20Ghostform/" height="300px">

**Comment by Kalioc** [comment]
Duplicate issue.
https://github.com/PennyDreadfulMTG/modo-bugs/issues/903
