### ISSUE TITLE
Erayo, Soratami Ascendant's other side is considered illegal in PD by PDBot

### ISSUE THREAD

**Issue by NEN3President** [PennyDreadfulMTG/modo-bugs#931]
**What is the expected behaviour of the card?**
 - Bot considers Erayo's Essence legal

**What is the actual behaviour of the card?**
 - Bot says Erayo is illegal and invalidates the match
Currently Unconfirmed.
![image](https://user-images.githubusercontent.com/86558343/123545482-9dbfeb00-d72e-11eb-8287-eaa1db8449a3.png)

**Please provide a list of affected cards**
Affects: [Erayo, Soratami Ascendant]
**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Erayo%2C%20Soratami%20Ascendant/" height="300px">

**Comment by Kalioc** [comment]
This is exclusively for MTGO bugs. PDBot issues are tracked separately.
https://github.com/PennyDreadfulMTG/Penny-Dreadful-Tools/issues/8727
