### ISSUE TITLE
Possibility Storm will check for both types on an Adventure card.

### ISSUE THREAD

**Issue by Kalioc** [PennyDreadfulMTG/modo-bugs#935]
**What is the expected behaviour of the card?**
 - Possibility Storm should exile a spell and exile cards from the top of the library until a card that shares the spell's type is found.

**What is the actual behaviour of the card?**
 - For Adventure cards, Possiblity Storm will also stop at creatures if the Adventure-side was cast.

**Screenshot**
![image](https://cdn.discordapp.com/attachments/321720972665290762/871931969745846292/unknown.png)
![image](https://user-images.githubusercontent.com/9436442/127945154-1a9cf139-7415-4a5f-8cdb-6c035638d239.png)

**Please provide a list of affected cards**
Affects: [Possibility Storm]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Possibility%20Storm/" height="300px">

**Comment by datrobino** [comment]
still bugged

**Comment by Kalioc** [comment]
![image](https://user-images.githubusercontent.com/9436442/175435875-dcbd1d4d-6f26-4da9-b8b2-670b29b8b112.png)
Fixed. 🙏
