### ISSUE TITLE
Some forms of gaining and losing life break the game

### ISSUE THREAD

**Issue by bakert** [PennyDreadfulMTG/modo-bugs#941]
**What is the expected behaviour of the card?**
 - You gain life based on checking something

**What is the actual behaviour of the card?**
 - The life gain repeats infinitely and you cannot proceed with the game

**Screenshot**

**Please provide a list of affected cards**
Affects: [Glimmerpost][An-Havva Inn][Search for Glory][Champion of Dusk][Alert Heedbonder][Fumigate][Take Heart][Graveborn Muse][Skeletal Scrying][Gnaw to the Bone]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Glimmerpost|An-Havva%20Inn|Search%20for%20Glory|Champion%20of%20Dusk/" height="300px"><img src="https://pennydreadfulmagic.com/image/Alert%20Heedbonder|Fumigate|Take%20Heart|Graveborn%20Muse/" height="300px"><img src="https://pennydreadfulmagic.com/image/Skeletal%20Scrying|Gnaw%20to%20the%20Bone/" height="300px">

**Comment by jtmeskil** [comment]
This has been resolved!

**Comment by bakert** [comment]
Woop.
