### ISSUE TITLE
Fiery Justice doesn't give the opponent life

### ISSUE THREAD

**Issue by MultiDragon** [PennyDreadfulMTG/modo-bugs#943]
**What is the expected behaviour of the card?**
 - When Fiery Justice is cast, you target an opponent, and that player gains 5 life when the spell resolves.

**What is the actual behaviour of the card?**
 - The targeted player doesn't gain 5 life on resolution.

**Screenshot**
![image](https://user-images.githubusercontent.com/52964431/136438188-66540c7a-0397-43e5-8596-217b24427372.png)

![image](https://user-images.githubusercontent.com/52964431/136438218-67225a54-0f2f-4428-8800-cda5dcd5514b.png)

**Please provide a list of affected cards**
Affects: [Fiery Justice]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Fiery%20Justice/" height="300px">

**Comment by bakert** [comment]
Plrt v Murpady confirmed this is no longer bugged.
