### ISSUE TITLE
Some cards that check board state fail under unknown circumstances

### ISSUE THREAD

**Issue by MultiDragon** [PennyDreadfulMTG/modo-bugs#944]
**What is the expected behaviour of the card?**
 - With Worship and a creature in play, damage putting those cards' controller to less than 1 is prevented. Lofty Denial counters spell unless the opponent pays 4 mana if a creature with flying is in play, and Stubborn Denial counters the spell without the payment option if its controller has ferocious.

**What is the actual behaviour of the card?**
 - Under unknown circumstances, the cards in question don't work.

Stubborn Denial and Lofty Denial can be considered advantageous when their controller counters their own spell but usually bad. Worship is close to strictly disadvantageous.

**Screenshot**
Worship
![image1](https://user-images.githubusercontent.com/52964431/134023831-9c66ef65-75b8-4a5c-8d77-552b42fdcbd1.png)
https://www.youtube.com/watch?v=jumlqlqxu_s&t=620s

Lofty Denial
![image2](https://user-images.githubusercontent.com/52964431/134023883-d20570ab-d41e-4210-8536-b8f0183aa3cd.png)
![image3](https://user-images.githubusercontent.com/52964431/134023898-8d6b6f92-99fb-40d2-b770-2bda7a829ec0.png)

Stubborn Denial unconfirmed.

**Please provide a list of affected cards**
Affects: [Worship], [Lofty Denial], [Stubborn Denial]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Worship|Lofty%20Denial|Stubborn%20Denial/" height="300px">

**Comment by david-sway** [comment]
Twitch streamer aspiringspike attacked his opponent to -3 life in spite of his opponent having two Worships and a Sylvan Caryatid on the battlefield.

https://www.youtube.com/watch?v=jumlqlqxu_s&t=620s

**Comment by Kalioc** [comment]
Removing Elderscale Wurm. It doesn't seem to fail randomly. #959 is separate issue for Elderscale Wurm.
