### ISSUE TITLE
Split cards can't gain flashback.

### ISSUE THREAD

**Issue by Kalioc** [PennyDreadfulMTG/modo-bugs#957]
**What is the expected behaviour of the card?**
 - A split cards gaining flashback should have a flashback cost for each side.

**What is the actual behaviour of the card?**
 - Split cards fail to gain flashback.

**Screenshot**
![image](https://user-images.githubusercontent.com/9436442/137767800-48ee3a4c-fea2-43e9-97bf-91f42be9c66f.png)

**Please provide a list of affected cards**
Affects: [Snapcaster Mage], [Recoup], etc.

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Snapcaster%20Mage|Recoup/" height="300px">

**Comment by datrobino** [comment]
idk where to add the video so i will put it here
https://youtu.be/9hrxo1ROAiI?t=445

**Comment by datrobino** [comment]
fixed, tested with backdraft hellkite and catch/release
