### ISSUE TITLE
Elderscale Wurm doesn't work if you are above 7 life

### ISSUE THREAD

**Issue by r7shooter00** [PennyDreadfulMTG/modo-bugs#959]
**What is the expected behaviour of the card?**
 -If you're life total is greater than or equal to 7, any damage that would lower your life total to less than 7 should reduce it to 7 instead.

**What is the actual behaviour of the card?**
 -If your life total is greater than 7, your life total will go below 7 if you take lethal damage. Otherwise it will go to 7 if you take nonlethal damage. If your life total is exactly 7, it will stay at 7.

**Screenshot**
https://imgur.com/a/0R961IN

**Please provide a list of affected cards**
Affects: [Elderscale Wurm]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Elderscale%20Wurm/" height="300px">

**Comment by Kalioc** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/9436442/143774741-e9864ae5-c5ff-48f9-9662-7d034d65c511.png)
![image](https://user-images.githubusercontent.com/9436442/143774753-3e524515-ecdf-44f5-a979-977e5b6dee2d.png)
