### ISSUE TITLE
Painful Truths gets stuck on OK if no colors of mana was spent to cast it.

### ISSUE THREAD

**Issue by zinnerzPT** [PennyDreadfulMTG/modo-bugs#968]
**What is the expected behaviour of the card?**
 - The spell is supposed to resolve doing nothing.

**What is the actual behaviour of the card?**
 - The "OK" prompt to proceed in the game doesn't proceed with the game.

**Screenshot**
https://youtu.be/ISg34nluCO4?t=3990

**Please provide a list of affected cards**
Affects: [Painful Truths]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Painful%20Truths/" height="300px">

**Comment by datrobino** [comment]
do we know when this video was filmed? it looks a lot like https://github.com/PennyDreadfulMTG/modo-bugs/issues/941 and   when i test it this works fine

**Comment by zinnerzPT** [comment]
Looking at the release date, it was definitely recorded before that other issue was closed, so it might be the same bug.
When I reported it, I had assumed it was a new video, but it turns out it is a few months old, so it might be fixed.
I did not test it myself

**Comment by datrobino** [comment]
i think i will close this one until someone else experiences a problem
