### ISSUE TITLE
Harmonic Prodigy triggers it's own prowess effect twice

### ISSUE THREAD

**Issue by datrobino** [PennyDreadfulMTG/modo-bugs#970]
**What is the expected behaviour of the card?**
 - Harmonic Prodigy should cause other wizards and shamans to trigger twice

**What is the actual behaviour of the card?**
 - Harmonic Prodigy allows itself to trigger twice

**Screenshot**
![image](https://user-images.githubusercontent.com/85389721/140989997-321cdff2-d1a3-457c-abc0-766305938284.png)
**Please provide a list of affected cards**
Affects: [Harmonic Prodigy]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Harmonic%20Prodigy/" height="300px">

**Comment by datrobino** [comment]
maybe should merge this, https://github.com/PennyDreadfulMTG/modo-bugs/issues/946, https://github.com/PennyDreadfulMTG/modo-bugs/issues/930, and https://github.com/PennyDreadfulMTG/modo-bugs/issues/928

**Comment by Kalioc** [comment]
I think #928 and #946 make sense to merge. This specific issue is probably related to #961. I don't think #930 should be merged to anything.
