### ISSUE TITLE
Nullstone Gargoyle counters all noncreature spells

### ISSUE THREAD

**Issue by cnelson20** [PennyDreadfulMTG/modo-bugs#976]
**What is the expected behaviour of the card?**
 - Nullstone Gargoyle should trigger on the casting of, and counter the first noncreature spell cast each turn.

**What is the actual behaviour of the card?**
 - It triggers on (and counters) every noncreature spell cast.

**Screenshot**
![image](https://user-images.githubusercontent.com/72891927/143505054-5857b036-3ed2-43f7-bc6e-fe1a96ca0478.png)

**Please provide a list of affected cards**
[Nullstone Gargoyle]

**Card Images**
 This section is automatically generated from the above list of cards.  You don't need to do anything.

**Comment by Kalioc** [comment]
Known issue (#615), closing because it's a duplicate.
