### ISSUE TITLE
Consuming Tide counts tokens that were bounced as in your hand for purposes of card draw.

### ISSUE THREAD

**Issue by ciabhanconnelly** [PennyDreadfulMTG/modo-bugs#982]
**What is the expected behaviour of the card?**
Consuming Tide should draw the controlling player a card for each opponent who has more cards in hand than the controlling player.

**What is the actual behaviour of the card?**
Sometimes Consuming Tide draws a card when the controlling player has more cards in hand than all opponents. This may be related to returning tokens to hand, and the game counting them among cards in hand when they are not. 

**Screenshot**
Currently Unconfirmed.

**Please provide a list of affected cards**
Affects: [Consuming Tide]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Consuming%20Tide/" height="300px">

**Comment by silasary** [comment]
Closing in favour of #1047
