### ISSUE TITLE
Laelia, the Blade Reforged doesn't trigger on Hideaway

### ISSUE THREAD

**Issue by Wizzerinus** [PennyDreadfulMTG/modo-bugs#987]
**What is the expected behaviour of the card?**
 - Whenever one or more cards are put into exile from your library, put a +1/+1 counter on Laelia, the Blade Reforged.

**What is the actual behaviour of the card?**
 - Hideaway doesn't cause Laelia to trigger.

**Screenshot**
![image](https://user-images.githubusercontent.com/52964431/147361029-7ab3207c-f94c-483a-8b78-9d266849ef90.png)

![image](https://user-images.githubusercontent.com/52964431/147361445-5520bae7-1bb0-4ec2-aeb2-544351783d11.png)

**Please provide a list of affected cards**
Affects: [Laelia, the Blade Reforged]

**Card Images**
 <img src="https://pennydreadfulmagic.com/image/Laelia%2C%20the%20Blade%20Reforged/" height="300px">

**Comment by bakert** [comment]
<img width="1871" alt="image" src="https://github.com/user-attachments/assets/3c4e9a24-dacf-4995-9510-0db36914e536">

This has been fixed at some point
